In [158]:
import pandas as pd

In [159]:
df = pd.read_json("raw_deals.json")

In [160]:
df

,product,discount,link,store,date
0,AH Aardappelpartjes Provençaals gekruid 600 gram,[Klikbaar:AH Aardappelpartjes Provençaals gekr...,https://www.ah.nl/bonus/groep/766837?week=9,Albertijn,23 feb t/m 1 mrt
1,AH Geschrapte worteltjes 500 gram,"[Klikbaar:AH Geschrapte worteltjes 500 gram, 2...",https://www.ah.nl/bonus/groep/766809?week=9,Albertijn,23 feb t/m 1 mrt
2,AH Rucola 85 gram,"[Klikbaar:AH Rucola 85 gram, voor 0.99]",https://www.ah.nl/bonus/groep/766835?week=9,Albertijn,23 feb t/m 1 mrt
3,AH Biologisch winterpeen 750 gram en AH Biolog...,[Klikbaar:AH Biologisch winterpeen 750 gram en...,https://www.ah.nl/bonus/groep/775045?week=9,Albertijn,23 feb t/m 1 mrt
4,Alle AH Italiaanse verspakketten,"[Klikbaar:Alle AH Italiaanse verspakketten, €1...",https://www.ah.nl/bonus/groep/766864?week=9,Albertijn,23 feb t/m 1 mrt
...,...,...,...,...,...
190,Gliss haarverzorging,"[Klikbaar:Gliss haarverzorging, 1+1 gratis, Bi...",https://www.ah.nl/bonus/groep/-21209?week=9,Albertijn,23 feb t/m 1 mrt
191,Garnier gezichtsverzorging,"[Klikbaar:Garnier gezichtsverzorging, 1+1 grat...",https://www.ah.nl/bonus/groep/-21207?week=9,Albertijn,23 feb t/m 1 mrt
192,Etos gezichtsverzorging,"[Klikbaar:Etos gezichtsverzorging, 2e halve pr...",https://www.ah.nl/bonus/groep/-21196?week=9,Albertijn,23 feb t/m 1 mrt
193,Biodermal,"[Klikbaar:Biodermal, 50% korting, Bijv. Bioder...",https://www.ah.nl/bonus/groep/-21194?week=9,Albertijn,23 feb t/m 1 mrt
194,Batiste,"[Klikbaar:Batiste, 2e halve prijs, 200 ml, All...",https://www.ah.nl/bonus/groep/-21193?week=9,Albertijn,23 feb t/m 1 mrt

In [161]:
df["date"] = df["date"].str.replace(" t/m ", " ")
def date_fixer(df):
    patern = r'\d+\s\w+'
    df["start_date"] = df["date"].str.findall(patern).str[0]
    df["end_date"] = df["date"].str.findall(patern).str[1]
    return df

df = date_fixer(df)
df = df.drop("date", axis = 1)

In [162]:
df["discount"] = df["discount"].str[0]
df

,product,discount,link,store,start_date,end_date
0,AH Aardappelpartjes Provençaals gekruid 600 gram,Klikbaar:AH Aardappelpartjes Provençaals gekru...,https://www.ah.nl/bonus/groep/766837?week=9,Albertijn,23 feb,1 mrt
1,AH Geschrapte worteltjes 500 gram,"Klikbaar:AH Geschrapte worteltjes 500 gram, 2e...",https://www.ah.nl/bonus/groep/766809?week=9,Albertijn,23 feb,1 mrt
2,AH Rucola 85 gram,"Klikbaar:AH Rucola 85 gram, voor 0.99",https://www.ah.nl/bonus/groep/766835?week=9,Albertijn,23 feb,1 mrt
3,AH Biologisch winterpeen 750 gram en AH Biolog...,Klikbaar:AH Biologisch winterpeen 750 gram en ...,https://www.ah.nl/bonus/groep/775045?week=9,Albertijn,23 feb,1 mrt
4,Alle AH Italiaanse verspakketten,"Klikbaar:Alle AH Italiaanse verspakketten, €1 ...",https://www.ah.nl/bonus/groep/766864?week=9,Albertijn,23 feb,1 mrt
...,...,...,...,...,...,...
190,Gliss haarverzorging,"Klikbaar:Gliss haarverzorging, 1+1 gratis, Bij...",https://www.ah.nl/bonus/groep/-21209?week=9,Albertijn,23 feb,1 mrt
191,Garnier gezichtsverzorging,"Klikbaar:Garnier gezichtsverzorging, 1+1 grati...",https://www.ah.nl/bonus/groep/-21207?week=9,Albertijn,23 feb,1 mrt
192,Etos gezichtsverzorging,"Klikbaar:Etos gezichtsverzorging, 2e halve pri...",https://www.ah.nl/bonus/groep/-21196?week=9,Albertijn,23 feb,1 mrt
193,Biodermal,"Klikbaar:Biodermal, 50% korting, Bijv. Bioderm...",https://www.ah.nl/bonus/groep/-21194?week=9,Albertijn,23 feb,1 mrt
194,Batiste,"Klikbaar:Batiste, 2e halve prijs, 200 ml, Alle...",https://www.ah.nl/bonus/groep/-21193?week=9,Albertijn,23 feb,1 mrt

In [163]:
df["discount"] = df["discount"].str.split(":")

In [164]:
df["discount"] = df["discount"].str[1]
df

,product,discount,link,store,start_date,end_date
0,AH Aardappelpartjes Provençaals gekruid 600 gram,AH Aardappelpartjes Provençaals gekruid 600 gr...,https://www.ah.nl/bonus/groep/766837?week=9,Albertijn,23 feb,1 mrt
1,AH Geschrapte worteltjes 500 gram,"AH Geschrapte worteltjes 500 gram, 2e gratis",https://www.ah.nl/bonus/groep/766809?week=9,Albertijn,23 feb,1 mrt
2,AH Rucola 85 gram,"AH Rucola 85 gram, voor 0.99",https://www.ah.nl/bonus/groep/766835?week=9,Albertijn,23 feb,1 mrt
3,AH Biologisch winterpeen 750 gram en AH Biolog...,AH Biologisch winterpeen 750 gram en AH Biolog...,https://www.ah.nl/bonus/groep/775045?week=9,Albertijn,23 feb,1 mrt
4,Alle AH Italiaanse verspakketten,"Alle AH Italiaanse verspakketten, €1 korting",https://www.ah.nl/bonus/groep/766864?week=9,Albertijn,23 feb,1 mrt
...,...,...,...,...,...,...
190,Gliss haarverzorging,"Gliss haarverzorging, 1+1 gratis, Bijv. Gliss ...",https://www.ah.nl/bonus/groep/-21209?week=9,Albertijn,23 feb,1 mrt
191,Garnier gezichtsverzorging,"Garnier gezichtsverzorging, 1+1 gratis, Bijv. ...",https://www.ah.nl/bonus/groep/-21207?week=9,Albertijn,23 feb,1 mrt
192,Etos gezichtsverzorging,"Etos gezichtsverzorging, 2e halve prijs, Bijv....",https://www.ah.nl/bonus/groep/-21196?week=9,Albertijn,23 feb,1 mrt
193,Biodermal,"Biodermal, 50% korting, Bijv. Biodermal Dag- &...",https://www.ah.nl/bonus/groep/-21194?week=9,Albertijn,23 feb,1 mrt
194,Batiste,"Batiste, 2e halve prijs, 200 ml, Alleen in de ...",https://www.ah.nl/bonus/groep/-21193?week=9,Albertijn,23 feb,1 mrt