In [49]:
import pandas as pd

In [84]:
df = pd.read_json("new_raw_deals.json")

In [85]:
df

,product,discount,link,store,date
0,Alle Hak*,[Klikbaar: Alle Hak* *M.u.v. taart & vlaaifrui...,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 t/m 10 mei
1,AH Courgette,[Klikbaar: AH Courgette 2 voor 1.49],https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 t/m 10 mei
2,AH Prei,[Klikbaar: AH Prei 2 voor 0.89],https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 t/m 10 mei
3,AH Iets kruimige aardappel 3 kilo,[Klikbaar: AH Iets kruimige aardappel 3 kilo 2...,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 t/m 10 mei
4,Alle AH Roerbakgroenten 400 gram,[Klikbaar: Alle AH Roerbakgroenten 400 gram 2 ...,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 t/m 10 mei
...,...,...,...,...,...
193,Gillette Mach 3 scheersysteem turbo 2,[Klikbaar: Gillette Mach 3 scheersysteem turbo...,https://www.ah.nl/bonus/groep/-21601?week=19,Albertijn,4 t/m 10 mei
194,Garnier gezichtsverzorging,[Klikbaar: Garnier gezichtsverzorging Bijv. Ga...,https://www.ah.nl/bonus/groep/-21600?week=19,Albertijn,4 t/m 10 mei
195,Etos tandenborstel,[Klikbaar: Etos tandenborstel 1 stuks 2e halve...,https://www.ah.nl/bonus/groep/-21597?week=19,Albertijn,4 t/m 10 mei
196,Etos gezichtsverzorging,[Klikbaar: Etos gezichtsverzorging Bijv. Etos ...,https://www.ah.nl/bonus/groep/-21591?week=19,Albertijn,4 t/m 10 mei
197,Drs Leenarts,[Klikbaar: Drs Leenarts Bijv. Drs. Leenarts Da...,https://www.ah.nl/bonus/groep/-21588?week=19,Albertijn,4 t/m 10 mei

In [86]:
df["date"] = df["date"].str.replace(" t/m ", " ")
df["date"]
def date_fixer(df):
    date = df["date"].str.split(expand=True)
    start = date[0]
    end = date[1]
    month = date[2]
    start_date = start + " " + month
    end_date = end + " " + month
    df["start_date"] = start_date
    df["end_date"] = end_date
    return df

df = date_fixer(df)
df = df.drop("date", axis=1)
df

,product,discount,link,store,start_date,end_date
0,Alle Hak*,[Klikbaar: Alle Hak* *M.u.v. taart & vlaaifrui...,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,[Klikbaar: AH Courgette 2 voor 1.49],https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,[Klikbaar: AH Prei 2 voor 0.89],https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,[Klikbaar: AH Iets kruimige aardappel 3 kilo 2...,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,[Klikbaar: Alle AH Roerbakgroenten 400 gram 2 ...,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
193,Gillette Mach 3 scheersysteem turbo 2,[Klikbaar: Gillette Mach 3 scheersysteem turbo...,https://www.ah.nl/bonus/groep/-21601?week=19,Albertijn,4 mei,10 mei
194,Garnier gezichtsverzorging,[Klikbaar: Garnier gezichtsverzorging Bijv. Ga...,https://www.ah.nl/bonus/groep/-21600?week=19,Albertijn,4 mei,10 mei
195,Etos tandenborstel,[Klikbaar: Etos tandenborstel 1 stuks 2e halve...,https://www.ah.nl/bonus/groep/-21597?week=19,Albertijn,4 mei,10 mei
196,Etos gezichtsverzorging,[Klikbaar: Etos gezichtsverzorging Bijv. Etos ...,https://www.ah.nl/bonus/groep/-21591?week=19,Albertijn,4 mei,10 mei
197,Drs Leenarts,[Klikbaar: Drs Leenarts Bijv. Drs. Leenarts Da...,https://www.ah.nl/bonus/groep/-21588?week=19,Albertijn,4 mei,10 mei

In [87]:
df["discount"] = df["discount"].str[0]
df

,product,discount,link,store,start_date,end_date
0,Alle Hak*,Klikbaar: Alle Hak* *M.u.v. taart & vlaaifruit...,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,Klikbaar: AH Courgette 2 voor 1.49,https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,Klikbaar: AH Prei 2 voor 0.89,https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,Klikbaar: AH Iets kruimige aardappel 3 kilo 2e...,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,Klikbaar: Alle AH Roerbakgroenten 400 gram 2 v...,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
193,Gillette Mach 3 scheersysteem turbo 2,Klikbaar: Gillette Mach 3 scheersysteem turbo ...,https://www.ah.nl/bonus/groep/-21601?week=19,Albertijn,4 mei,10 mei
194,Garnier gezichtsverzorging,Klikbaar: Garnier gezichtsverzorging Bijv. Gar...,https://www.ah.nl/bonus/groep/-21600?week=19,Albertijn,4 mei,10 mei
195,Etos tandenborstel,Klikbaar: Etos tandenborstel 1 stuks 2e halve ...,https://www.ah.nl/bonus/groep/-21597?week=19,Albertijn,4 mei,10 mei
196,Etos gezichtsverzorging,Klikbaar: Etos gezichtsverzorging Bijv. Etos E...,https://www.ah.nl/bonus/groep/-21591?week=19,Albertijn,4 mei,10 mei
197,Drs Leenarts,Klikbaar: Drs Leenarts Bijv. Drs. Leenarts Dag...,https://www.ah.nl/bonus/groep/-21588?week=19,Albertijn,4 mei,10 mei

In [88]:
df["discount"] = df["discount"].str.split(":")
df

,product,discount,link,store,start_date,end_date
0,Alle Hak*,"[Klikbaar, Alle Hak* *M.u.v. taart & vlaaifru...",https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,"[Klikbaar, AH Courgette 2 voor 1.49]",https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,"[Klikbaar, AH Prei 2 voor 0.89]",https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,"[Klikbaar, AH Iets kruimige aardappel 3 kilo ...",https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,"[Klikbaar, Alle AH Roerbakgroenten 400 gram 2...",https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
193,Gillette Mach 3 scheersysteem turbo 2,"[Klikbaar, Gillette Mach 3 scheersysteem turb...",https://www.ah.nl/bonus/groep/-21601?week=19,Albertijn,4 mei,10 mei
194,Garnier gezichtsverzorging,"[Klikbaar, Garnier gezichtsverzorging Bijv. G...",https://www.ah.nl/bonus/groep/-21600?week=19,Albertijn,4 mei,10 mei
195,Etos tandenborstel,"[Klikbaar, Etos tandenborstel 1 stuks 2e halv...",https://www.ah.nl/bonus/groep/-21597?week=19,Albertijn,4 mei,10 mei
196,Etos gezichtsverzorging,"[Klikbaar, Etos gezichtsverzorging Bijv. Etos...",https://www.ah.nl/bonus/groep/-21591?week=19,Albertijn,4 mei,10 mei
197,Drs Leenarts,"[Klikbaar, Drs Leenarts Bijv. Drs. Leenarts D...",https://www.ah.nl/bonus/groep/-21588?week=19,Albertijn,4 mei,10 mei

In [89]:
df["discount"] = df["discount"].str[1]
df

,product,discount,link,store,start_date,end_date
0,Alle Hak*,Alle Hak* *M.u.v. taart & vlaaifruit uitgelic...,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,AH Courgette 2 voor 1.49,https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,AH Prei 2 voor 0.89,https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,AH Iets kruimige aardappel 3 kilo 2e gratis,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,Alle AH Roerbakgroenten 400 gram 2 voor 3.99,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
193,Gillette Mach 3 scheersysteem turbo 2,Gillette Mach 3 scheersysteem turbo 2 1 stuks...,https://www.ah.nl/bonus/groep/-21601?week=19,Albertijn,4 mei,10 mei
194,Garnier gezichtsverzorging,Garnier gezichtsverzorging Bijv. Garnier Skin...,https://www.ah.nl/bonus/groep/-21600?week=19,Albertijn,4 mei,10 mei
195,Etos tandenborstel,Etos tandenborstel 1 stuks 2e halve prijs van...,https://www.ah.nl/bonus/groep/-21597?week=19,Albertijn,4 mei,10 mei
196,Etos gezichtsverzorging,Etos gezichtsverzorging Bijv. Etos Eye make-u...,https://www.ah.nl/bonus/groep/-21591?week=19,Albertijn,4 mei,10 mei
197,Drs Leenarts,Drs Leenarts Bijv. Drs. Leenarts Dagcreme SPF...,https://www.ah.nl/bonus/groep/-21588?week=19,Albertijn,4 mei,10 mei

In [90]:
#Deleting all rows which have bezorging.
df = df[~df["product"].str.contains("bezorging", case=False, na=False)]
df

,product,discount,link,store,start_date,end_date
0,Alle Hak*,Alle Hak* *M.u.v. taart & vlaaifruit uitgelic...,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,AH Courgette 2 voor 1.49,https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,AH Prei 2 voor 0.89,https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,AH Iets kruimige aardappel 3 kilo 2e gratis,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,Alle AH Roerbakgroenten 400 gram 2 voor 3.99,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
193,Gillette Mach 3 scheersysteem turbo 2,Gillette Mach 3 scheersysteem turbo 2 1 stuks...,https://www.ah.nl/bonus/groep/-21601?week=19,Albertijn,4 mei,10 mei
194,Garnier gezichtsverzorging,Garnier gezichtsverzorging Bijv. Garnier Skin...,https://www.ah.nl/bonus/groep/-21600?week=19,Albertijn,4 mei,10 mei
195,Etos tandenborstel,Etos tandenborstel 1 stuks 2e halve prijs van...,https://www.ah.nl/bonus/groep/-21597?week=19,Albertijn,4 mei,10 mei
196,Etos gezichtsverzorging,Etos gezichtsverzorging Bijv. Etos Eye make-u...,https://www.ah.nl/bonus/groep/-21591?week=19,Albertijn,4 mei,10 mei
197,Drs Leenarts,Drs Leenarts Bijv. Drs. Leenarts Dagcreme SPF...,https://www.ah.nl/bonus/groep/-21588?week=19,Albertijn,4 mei,10 mei

In [91]:
df = df[~df["product"].str.contains("Online", case=True, na=False)]
df

,product,discount,link,store,start_date,end_date
0,Alle Hak*,Alle Hak* *M.u.v. taart & vlaaifruit uitgelic...,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,AH Courgette 2 voor 1.49,https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,AH Prei 2 voor 0.89,https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,AH Iets kruimige aardappel 3 kilo 2e gratis,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,Alle AH Roerbakgroenten 400 gram 2 voor 3.99,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
193,Gillette Mach 3 scheersysteem turbo 2,Gillette Mach 3 scheersysteem turbo 2 1 stuks...,https://www.ah.nl/bonus/groep/-21601?week=19,Albertijn,4 mei,10 mei
194,Garnier gezichtsverzorging,Garnier gezichtsverzorging Bijv. Garnier Skin...,https://www.ah.nl/bonus/groep/-21600?week=19,Albertijn,4 mei,10 mei
195,Etos tandenborstel,Etos tandenborstel 1 stuks 2e halve prijs van...,https://www.ah.nl/bonus/groep/-21597?week=19,Albertijn,4 mei,10 mei
196,Etos gezichtsverzorging,Etos gezichtsverzorging Bijv. Etos Eye make-u...,https://www.ah.nl/bonus/groep/-21591?week=19,Albertijn,4 mei,10 mei
197,Drs Leenarts,Drs Leenarts Bijv. Drs. Leenarts Dagcreme SPF...,https://www.ah.nl/bonus/groep/-21588?week=19,Albertijn,4 mei,10 mei

In [92]:
#Removing all products which are online
target_index = df[df["product"].str.contains("OP=OP", case=True, na=False)].index[0]
df = df.loc[:target_index - 1]
df

,product,discount,link,store,start_date,end_date
0,Alle Hak*,Alle Hak* *M.u.v. taart & vlaaifruit uitgelic...,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,AH Courgette 2 voor 1.49,https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,AH Prei 2 voor 0.89,https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,AH Iets kruimige aardappel 3 kilo 2e gratis,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,Alle AH Roerbakgroenten 400 gram 2 voor 3.99,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
138,Weber BBQ accessoires,Weber BBQ accessoires Bonus,https://www.ah.nl/bonus/groep/779600?week=19,Albertijn,4 mei,10 mei
139,Grill Guru Houtskool 10 kilo,Grill Guru Houtskool 10 kilo voor 18.95 van 2...,https://www.ah.nl/bonus/groep/779602?week=19,Albertijn,4 mei,10 mei
140,Grill Guru BBQ accessoires,Grill Guru BBQ accessoires 25% korting,https://www.ah.nl/bonus/groep/779606?week=19,Albertijn,4 mei,10 mei
141,AH Hortensia of bougainvillea in mand,AH Hortensia of bougainvillea in mand voor 15...,https://www.ah.nl/bonus/groep/787728?week=19,Albertijn,4 mei,10 mei
142,AH Moederdagboeketten,AH Moederdagboeketten Bonus Alleen in de winkel,https://www.ah.nl/bonus/groep/788994?week=19,Albertijn,4 mei,10 mei

In [93]:
import re

def discount_clean(text):
    pattern = r'(van \d*\.?\d* voor \d*\.?\d*)'
    match = re.search(pattern, text)
    if match:
        return match.group(1)
    else:
        return text
df["discount"] = df["discount"].apply(discount_clean)
df

,product,discount,link,store,start_date,end_date
0,Alle Hak*,Alle Hak* *M.u.v. taart & vlaaifruit uitgelic...,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,AH Courgette 2 voor 1.49,https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,AH Prei 2 voor 0.89,https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,AH Iets kruimige aardappel 3 kilo 2e gratis,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,Alle AH Roerbakgroenten 400 gram 2 voor 3.99,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
138,Weber BBQ accessoires,Weber BBQ accessoires Bonus,https://www.ah.nl/bonus/groep/779600?week=19,Albertijn,4 mei,10 mei
139,Grill Guru Houtskool 10 kilo,van 25.95 voor 18.95,https://www.ah.nl/bonus/groep/779602?week=19,Albertijn,4 mei,10 mei
140,Grill Guru BBQ accessoires,Grill Guru BBQ accessoires 25% korting,https://www.ah.nl/bonus/groep/779606?week=19,Albertijn,4 mei,10 mei
141,AH Hortensia of bougainvillea in mand,AH Hortensia of bougainvillea in mand voor 15...,https://www.ah.nl/bonus/groep/787728?week=19,Albertijn,4 mei,10 mei
142,AH Moederdagboeketten,AH Moederdagboeketten Bonus Alleen in de winkel,https://www.ah.nl/bonus/groep/788994?week=19,Albertijn,4 mei,10 mei

In [94]:
#handling the scenarios with voor only prices
def voor_filter(text):
    pattern = r'((?:\d+\W*?\w*\s+)?voor \d+\.?\d*)'
    text_van = r'(van \d*\.?\d* voor \d*\.?\d*)'
    text_pattern = re.search(text_van, text)
    if text_pattern:
        return text
    else:
        match = re.search(pattern, text)
        if match:
            return match.group(1)
        else:
            return text

df["discount"] = df["discount"].apply(voor_filter)
df

,product,discount,link,store,start_date,end_date
0,Alle Hak*,Alle Hak* *M.u.v. taart & vlaaifruit uitgelic...,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,2 voor 1.49,https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,2 voor 0.89,https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,AH Iets kruimige aardappel 3 kilo 2e gratis,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,2 voor 3.99,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
138,Weber BBQ accessoires,Weber BBQ accessoires Bonus,https://www.ah.nl/bonus/groep/779600?week=19,Albertijn,4 mei,10 mei
139,Grill Guru Houtskool 10 kilo,van 25.95 voor 18.95,https://www.ah.nl/bonus/groep/779602?week=19,Albertijn,4 mei,10 mei
140,Grill Guru BBQ accessoires,Grill Guru BBQ accessoires 25% korting,https://www.ah.nl/bonus/groep/779606?week=19,Albertijn,4 mei,10 mei
141,AH Hortensia of bougainvillea in mand,voor 15.00,https://www.ah.nl/bonus/groep/787728?week=19,Albertijn,4 mei,10 mei
142,AH Moederdagboeketten,AH Moederdagboeketten Bonus Alleen in de winkel,https://www.ah.nl/bonus/groep/788994?week=19,Albertijn,4 mei,10 mei

In [99]:
def discount_name_cleaner(row):
    discount = str(row["discount"])
    product = str(row["product"])
    if(product in discount):
        return discount.replace(product, "").strip()
    return discount

df_new = df.copy()
df_new["discount"] = df_new.apply(discount_name_cleaner, axis=1)
df_new

,product,discount,link,store,start_date,end_date
0,Alle Hak*,*M.u.v. taart & vlaaifruit uitgelicht 2e gratis,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,2 voor 1.49,https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,2 voor 0.89,https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,2e gratis,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,2 voor 3.99,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
138,Weber BBQ accessoires,Bonus,https://www.ah.nl/bonus/groep/779600?week=19,Albertijn,4 mei,10 mei
139,Grill Guru Houtskool 10 kilo,van 25.95 voor 18.95,https://www.ah.nl/bonus/groep/779602?week=19,Albertijn,4 mei,10 mei
140,Grill Guru BBQ accessoires,25% korting,https://www.ah.nl/bonus/groep/779606?week=19,Albertijn,4 mei,10 mei
141,AH Hortensia of bougainvillea in mand,voor 15.00,https://www.ah.nl/bonus/groep/787728?week=19,Albertijn,4 mei,10 mei
142,AH Moederdagboeketten,Bonus Alleen in de winkel,https://www.ah.nl/bonus/groep/788994?week=19,Albertijn,4 mei,10 mei

In [100]:
#removing Allen in winkel
def winkel(text):
    wink = "Alleen in de winkel"
    if wink in text:
        return text.replace(wink, "").strip()
    return text
df_new["discount"] = df_new["discount"].apply(winkel)
df_new

,product,discount,link,store,start_date,end_date
0,Alle Hak*,*M.u.v. taart & vlaaifruit uitgelicht 2e gratis,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 mei,10 mei
1,AH Courgette,2 voor 1.49,https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 mei,10 mei
2,AH Prei,2 voor 0.89,https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 mei,10 mei
3,AH Iets kruimige aardappel 3 kilo,2e gratis,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 mei,10 mei
4,Alle AH Roerbakgroenten 400 gram,2 voor 3.99,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 mei,10 mei
...,...,...,...,...,...,...
138,Weber BBQ accessoires,Bonus,https://www.ah.nl/bonus/groep/779600?week=19,Albertijn,4 mei,10 mei
139,Grill Guru Houtskool 10 kilo,van 25.95 voor 18.95,https://www.ah.nl/bonus/groep/779602?week=19,Albertijn,4 mei,10 mei
140,Grill Guru BBQ accessoires,25% korting,https://www.ah.nl/bonus/groep/779606?week=19,Albertijn,4 mei,10 mei
141,AH Hortensia of bougainvillea in mand,voor 15.00,https://www.ah.nl/bonus/groep/787728?week=19,Albertijn,4 mei,10 mei
142,AH Moederdagboeketten,Bonus,https://www.ah.nl/bonus/groep/788994?week=19,Albertijn,4 mei,10 mei

In [102]:
df_new.to_json('data/AH_cleaned_3.json', orient='records', indent=4, force_ascii=False)