In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../scraping/new_raw_deals.json", convert_dates=False)

In [3]:
df

,product,discount,link,store,date,image_url
0,Alle Hak glazen potten,[Klikbaar: Alle Hak glazen potten 1+1 gratis],https://www.ah.nl/bonus/groep/797134?week=25,Albertijn,15 t/m 21 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_1806...
1,AH Aubergine en courgette,[Klikbaar: AH Aubergine en courgette Los 2 voo...,https://www.ah.nl/bonus/groep/800241?week=25,Albertijn,15 t/m 21 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...
2,"AH Snoepgroente tomaat, tomatenmix en komkomme...","[Klikbaar: AH Snoepgroente tomaat, tomatenmix ...",https://www.ah.nl/bonus/groep/800243?week=25,Albertijn,15 t/m 21 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...
3,Alle AH Gekoelde bakaardappelen 600 gram,[Klikbaar: Alle AH Gekoelde bakaardappelen 600...,https://www.ah.nl/bonus/groep/791852?week=25,Albertijn,15 t/m 21 jun,https://static.ah.nl/dam/product/AHI_435452393...
4,AH Sweet Palermo rode puntpaprika 2 stuks,[Klikbaar: AH Sweet Palermo rode puntpaprika 2...,https://www.ah.nl/bonus/groep/800242?week=25,Albertijn,15 t/m 21 jun,https://static.ah.nl/dam/product/AHI_586776636...
...,...,...,...,...,...,...
247,Etos gezichtsverzorging,[Klikbaar: Etos gezichtsverzorging Bijv. Etos ...,https://www.ah.nl/bonus/groep/-21831?week=25,Albertijn,15 t/m 21 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
248,Drs Leenarts gezichtsverzorging,[Klikbaar: Drs Leenarts gezichtsverzorging Bij...,https://www.ah.nl/bonus/groep/-21826?week=25,Albertijn,15 t/m 21 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
249,Dermolin,[Klikbaar: Dermolin Bijv. Dermolin Shampoo - 2...,https://www.ah.nl/bonus/groep/-21825?week=25,Albertijn,15 t/m 21 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
250,Biodermal,[Klikbaar: Biodermal Bijv. Biodermal P-CL-E ha...,https://www.ah.nl/bonus/groep/-21822?week=25,Albertijn,15 t/m 21 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
251,Australian Gold Instant bronzer spray,[Klikbaar: Australian Gold Instant bronzer spr...,https://www.ah.nl/bonus/groep/-21820?week=25,Albertijn,15 t/m 21 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...

In [4]:
df["date"] = df["date"].str.replace(" t/m ", " ")
df["date"]
def date_fixer(df):
    date = df["date"].str.split(expand=True)
    start = date[0]
    end = date[1]
    month = date[2]
    start_date = start + " " + month
    end_date = end + " " + month
    df["start_date"] = start_date
    df["end_date"] = end_date
    return df

df = date_fixer(df)
df = df.drop("date", axis=1)
df

,product,discount,link,store,image_url,start_date,end_date
0,Alle Hak glazen potten,[Klikbaar: Alle Hak glazen potten 1+1 gratis],https://www.ah.nl/bonus/groep/797134?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1806...,15 jun,21 jun
1,AH Aubergine en courgette,[Klikbaar: AH Aubergine en courgette Los 2 voo...,https://www.ah.nl/bonus/groep/800241?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
2,"AH Snoepgroente tomaat, tomatenmix en komkomme...","[Klikbaar: AH Snoepgroente tomaat, tomatenmix ...",https://www.ah.nl/bonus/groep/800243?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
3,Alle AH Gekoelde bakaardappelen 600 gram,[Klikbaar: Alle AH Gekoelde bakaardappelen 600...,https://www.ah.nl/bonus/groep/791852?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,15 jun,21 jun
4,AH Sweet Palermo rode puntpaprika 2 stuks,[Klikbaar: AH Sweet Palermo rode puntpaprika 2...,https://www.ah.nl/bonus/groep/800242?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_586776636...,15 jun,21 jun
...,...,...,...,...,...,...,...
247,Etos gezichtsverzorging,[Klikbaar: Etos gezichtsverzorging Bijv. Etos ...,https://www.ah.nl/bonus/groep/-21831?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
248,Drs Leenarts gezichtsverzorging,[Klikbaar: Drs Leenarts gezichtsverzorging Bij...,https://www.ah.nl/bonus/groep/-21826?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
249,Dermolin,[Klikbaar: Dermolin Bijv. Dermolin Shampoo - 2...,https://www.ah.nl/bonus/groep/-21825?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
250,Biodermal,[Klikbaar: Biodermal Bijv. Biodermal P-CL-E ha...,https://www.ah.nl/bonus/groep/-21822?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
251,Australian Gold Instant bronzer spray,[Klikbaar: Australian Gold Instant bronzer spr...,https://www.ah.nl/bonus/groep/-21820?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun

In [5]:
df["discount"] = df["discount"].str[0]
df

,product,discount,link,store,image_url,start_date,end_date
0,Alle Hak glazen potten,Klikbaar: Alle Hak glazen potten 1+1 gratis,https://www.ah.nl/bonus/groep/797134?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1806...,15 jun,21 jun
1,AH Aubergine en courgette,Klikbaar: AH Aubergine en courgette Los 2 voor...,https://www.ah.nl/bonus/groep/800241?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
2,"AH Snoepgroente tomaat, tomatenmix en komkomme...","Klikbaar: AH Snoepgroente tomaat, tomatenmix e...",https://www.ah.nl/bonus/groep/800243?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
3,Alle AH Gekoelde bakaardappelen 600 gram,Klikbaar: Alle AH Gekoelde bakaardappelen 600 ...,https://www.ah.nl/bonus/groep/791852?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,15 jun,21 jun
4,AH Sweet Palermo rode puntpaprika 2 stuks,Klikbaar: AH Sweet Palermo rode puntpaprika 2 ...,https://www.ah.nl/bonus/groep/800242?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_586776636...,15 jun,21 jun
...,...,...,...,...,...,...,...
247,Etos gezichtsverzorging,Klikbaar: Etos gezichtsverzorging Bijv. Etos C...,https://www.ah.nl/bonus/groep/-21831?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
248,Drs Leenarts gezichtsverzorging,Klikbaar: Drs Leenarts gezichtsverzorging Bijv...,https://www.ah.nl/bonus/groep/-21826?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
249,Dermolin,Klikbaar: Dermolin Bijv. Dermolin Shampoo - 2 ...,https://www.ah.nl/bonus/groep/-21825?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
250,Biodermal,Klikbaar: Biodermal Bijv. Biodermal P-CL-E han...,https://www.ah.nl/bonus/groep/-21822?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
251,Australian Gold Instant bronzer spray,Klikbaar: Australian Gold Instant bronzer spra...,https://www.ah.nl/bonus/groep/-21820?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun

In [6]:
df["discount"] = df["discount"].str.split(":")
df

,product,discount,link,store,image_url,start_date,end_date
0,Alle Hak glazen potten,"[Klikbaar, Alle Hak glazen potten 1+1 gratis]",https://www.ah.nl/bonus/groep/797134?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1806...,15 jun,21 jun
1,AH Aubergine en courgette,"[Klikbaar, AH Aubergine en courgette Los 2 vo...",https://www.ah.nl/bonus/groep/800241?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
2,"AH Snoepgroente tomaat, tomatenmix en komkomme...","[Klikbaar, AH Snoepgroente tomaat, tomatenmix...",https://www.ah.nl/bonus/groep/800243?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
3,Alle AH Gekoelde bakaardappelen 600 gram,"[Klikbaar, Alle AH Gekoelde bakaardappelen 60...",https://www.ah.nl/bonus/groep/791852?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,15 jun,21 jun
4,AH Sweet Palermo rode puntpaprika 2 stuks,"[Klikbaar, AH Sweet Palermo rode puntpaprika ...",https://www.ah.nl/bonus/groep/800242?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_586776636...,15 jun,21 jun
...,...,...,...,...,...,...,...
247,Etos gezichtsverzorging,"[Klikbaar, Etos gezichtsverzorging Bijv. Etos...",https://www.ah.nl/bonus/groep/-21831?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
248,Drs Leenarts gezichtsverzorging,"[Klikbaar, Drs Leenarts gezichtsverzorging Bi...",https://www.ah.nl/bonus/groep/-21826?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
249,Dermolin,"[Klikbaar, Dermolin Bijv. Dermolin Shampoo - ...",https://www.ah.nl/bonus/groep/-21825?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
250,Biodermal,"[Klikbaar, Biodermal Bijv. Biodermal P-CL-E h...",https://www.ah.nl/bonus/groep/-21822?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
251,Australian Gold Instant bronzer spray,"[Klikbaar, Australian Gold Instant bronzer sp...",https://www.ah.nl/bonus/groep/-21820?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun

In [7]:
df["discount"] = df["discount"].str[1]
df

,product,discount,link,store,image_url,start_date,end_date
0,Alle Hak glazen potten,Alle Hak glazen potten 1+1 gratis,https://www.ah.nl/bonus/groep/797134?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1806...,15 jun,21 jun
1,AH Aubergine en courgette,AH Aubergine en courgette Los 2 voor 0.99,https://www.ah.nl/bonus/groep/800241?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
2,"AH Snoepgroente tomaat, tomatenmix en komkomme...","AH Snoepgroente tomaat, tomatenmix en komkomm...",https://www.ah.nl/bonus/groep/800243?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
3,Alle AH Gekoelde bakaardappelen 600 gram,Alle AH Gekoelde bakaardappelen 600 gram voor...,https://www.ah.nl/bonus/groep/791852?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,15 jun,21 jun
4,AH Sweet Palermo rode puntpaprika 2 stuks,AH Sweet Palermo rode puntpaprika 2 stuks 30%...,https://www.ah.nl/bonus/groep/800242?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_586776636...,15 jun,21 jun
...,...,...,...,...,...,...,...
247,Etos gezichtsverzorging,Etos gezichtsverzorging Bijv. Etos Cleansing ...,https://www.ah.nl/bonus/groep/-21831?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
248,Drs Leenarts gezichtsverzorging,Drs Leenarts gezichtsverzorging Bijv. Drs. Le...,https://www.ah.nl/bonus/groep/-21826?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
249,Dermolin,Dermolin Bijv. Dermolin Shampoo - 2 x 200 ml ...,https://www.ah.nl/bonus/groep/-21825?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
250,Biodermal,Biodermal Bijv. Biodermal P-CL-E handcreme - ...,https://www.ah.nl/bonus/groep/-21822?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
251,Australian Gold Instant bronzer spray,Australian Gold Instant bronzer spray Bijv. A...,https://www.ah.nl/bonus/groep/-21820?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun

In [8]:
#Deleting all rows which have bezorging.
df = df[~df["product"].str.contains("bezorging", case=False, na=False)]
df

,product,discount,link,store,image_url,start_date,end_date
0,Alle Hak glazen potten,Alle Hak glazen potten 1+1 gratis,https://www.ah.nl/bonus/groep/797134?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1806...,15 jun,21 jun
1,AH Aubergine en courgette,AH Aubergine en courgette Los 2 voor 0.99,https://www.ah.nl/bonus/groep/800241?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
2,"AH Snoepgroente tomaat, tomatenmix en komkomme...","AH Snoepgroente tomaat, tomatenmix en komkomm...",https://www.ah.nl/bonus/groep/800243?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
3,Alle AH Gekoelde bakaardappelen 600 gram,Alle AH Gekoelde bakaardappelen 600 gram voor...,https://www.ah.nl/bonus/groep/791852?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,15 jun,21 jun
4,AH Sweet Palermo rode puntpaprika 2 stuks,AH Sweet Palermo rode puntpaprika 2 stuks 30%...,https://www.ah.nl/bonus/groep/800242?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_586776636...,15 jun,21 jun
...,...,...,...,...,...,...,...
247,Etos gezichtsverzorging,Etos gezichtsverzorging Bijv. Etos Cleansing ...,https://www.ah.nl/bonus/groep/-21831?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
248,Drs Leenarts gezichtsverzorging,Drs Leenarts gezichtsverzorging Bijv. Drs. Le...,https://www.ah.nl/bonus/groep/-21826?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
249,Dermolin,Dermolin Bijv. Dermolin Shampoo - 2 x 200 ml ...,https://www.ah.nl/bonus/groep/-21825?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
250,Biodermal,Biodermal Bijv. Biodermal P-CL-E handcreme - ...,https://www.ah.nl/bonus/groep/-21822?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
251,Australian Gold Instant bronzer spray,Australian Gold Instant bronzer spray Bijv. A...,https://www.ah.nl/bonus/groep/-21820?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun

In [9]:
df = df[~df["product"].str.contains("Online", case=True, na=False)]
df

,product,discount,link,store,image_url,start_date,end_date
0,Alle Hak glazen potten,Alle Hak glazen potten 1+1 gratis,https://www.ah.nl/bonus/groep/797134?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1806...,15 jun,21 jun
1,AH Aubergine en courgette,AH Aubergine en courgette Los 2 voor 0.99,https://www.ah.nl/bonus/groep/800241?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
2,"AH Snoepgroente tomaat, tomatenmix en komkomme...","AH Snoepgroente tomaat, tomatenmix en komkomm...",https://www.ah.nl/bonus/groep/800243?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
3,Alle AH Gekoelde bakaardappelen 600 gram,Alle AH Gekoelde bakaardappelen 600 gram voor...,https://www.ah.nl/bonus/groep/791852?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,15 jun,21 jun
4,AH Sweet Palermo rode puntpaprika 2 stuks,AH Sweet Palermo rode puntpaprika 2 stuks 30%...,https://www.ah.nl/bonus/groep/800242?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_586776636...,15 jun,21 jun
...,...,...,...,...,...,...,...
247,Etos gezichtsverzorging,Etos gezichtsverzorging Bijv. Etos Cleansing ...,https://www.ah.nl/bonus/groep/-21831?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
248,Drs Leenarts gezichtsverzorging,Drs Leenarts gezichtsverzorging Bijv. Drs. Le...,https://www.ah.nl/bonus/groep/-21826?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
249,Dermolin,Dermolin Bijv. Dermolin Shampoo - 2 x 200 ml ...,https://www.ah.nl/bonus/groep/-21825?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
250,Biodermal,Biodermal Bijv. Biodermal P-CL-E handcreme - ...,https://www.ah.nl/bonus/groep/-21822?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun
251,Australian Gold Instant bronzer spray,Australian Gold Instant bronzer spray Bijv. A...,https://www.ah.nl/bonus/groep/-21820?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,15 jun,21 jun

In [10]:
#Removing all products which are online
target_index = df[df["product"].str.contains("OP=OP", case=True, na=False)].index[0]
df = df.loc[:target_index - 1]
df

,product,discount,link,store,image_url,start_date,end_date
0,Alle Hak glazen potten,Alle Hak glazen potten 1+1 gratis,https://www.ah.nl/bonus/groep/797134?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1806...,15 jun,21 jun
1,AH Aubergine en courgette,AH Aubergine en courgette Los 2 voor 0.99,https://www.ah.nl/bonus/groep/800241?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
2,"AH Snoepgroente tomaat, tomatenmix en komkomme...","AH Snoepgroente tomaat, tomatenmix en komkomm...",https://www.ah.nl/bonus/groep/800243?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
3,Alle AH Gekoelde bakaardappelen 600 gram,Alle AH Gekoelde bakaardappelen 600 gram voor...,https://www.ah.nl/bonus/groep/791852?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,15 jun,21 jun
4,AH Sweet Palermo rode puntpaprika 2 stuks,AH Sweet Palermo rode puntpaprika 2 stuks 30%...,https://www.ah.nl/bonus/groep/800242?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_586776636...,15 jun,21 jun
...,...,...,...,...,...,...,...
182,Grill Guru Houtskool 10 kilo,Grill Guru Houtskool 10 kilo voor 18.95,https://www.ah.nl/bonus/groep/779602?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,15 jun,21 jun
183,Grill Guru BBQ accessoires,Grill Guru BBQ accessoires 25% korting,https://www.ah.nl/bonus/groep/779606?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,15 jun,21 jun
184,WK Oranje accessoires,WK Oranje accessoires Bonus,https://www.ah.nl/bonus/groep/794267?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1777...,15 jun,21 jun
185,AH Ridderspoor,AH Ridderspoor voor 3.50 Alleen in de winkel,https://www.ah.nl/bonus/groep/799709?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_566634616...,15 jun,21 jun
186,Zomerdeals,Zomerdeals Bonus,https://www.ah.nl/bonus/groep/800531?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_68736b373...,15 jun,21 jun

In [11]:
def discount_name_cleaner(row):
    discount = str(row["discount"])
    product = str(row["product"])
    if(product in discount):
        return discount.replace(product, "").strip()
    return discount

df_new = df.copy()
df_new["discount"] = df_new.apply(discount_name_cleaner, axis=1)
df_new

,product,discount,link,store,image_url,start_date,end_date
0,Alle Hak glazen potten,1+1 gratis,https://www.ah.nl/bonus/groep/797134?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1806...,15 jun,21 jun
1,AH Aubergine en courgette,Los 2 voor 0.99,https://www.ah.nl/bonus/groep/800241?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
2,"AH Snoepgroente tomaat, tomatenmix en komkomme...",2 stuks 50% 1 stuk 35%,https://www.ah.nl/bonus/groep/800243?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
3,Alle AH Gekoelde bakaardappelen 600 gram,voor 0.89,https://www.ah.nl/bonus/groep/791852?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,15 jun,21 jun
4,AH Sweet Palermo rode puntpaprika 2 stuks,30% korting,https://www.ah.nl/bonus/groep/800242?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_586776636...,15 jun,21 jun
...,...,...,...,...,...,...,...
182,Grill Guru Houtskool 10 kilo,voor 18.95,https://www.ah.nl/bonus/groep/779602?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,15 jun,21 jun
183,Grill Guru BBQ accessoires,25% korting,https://www.ah.nl/bonus/groep/779606?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,15 jun,21 jun
184,WK Oranje accessoires,Bonus,https://www.ah.nl/bonus/groep/794267?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1777...,15 jun,21 jun
185,AH Ridderspoor,voor 3.50 Alleen in de winkel,https://www.ah.nl/bonus/groep/799709?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_566634616...,15 jun,21 jun
186,Zomerdeals,Bonus,https://www.ah.nl/bonus/groep/800531?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_68736b373...,15 jun,21 jun

In [12]:
#removing Allen in winkel
def winkel(text):
    wink = "Alleen in de winkel"
    if wink in text:
        return text.replace(wink, "").strip()
    return text
df_new["discount"] = df_new["discount"].apply(winkel)
df_new

,product,discount,link,store,image_url,start_date,end_date
0,Alle Hak glazen potten,1+1 gratis,https://www.ah.nl/bonus/groep/797134?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1806...,15 jun,21 jun
1,AH Aubergine en courgette,Los 2 voor 0.99,https://www.ah.nl/bonus/groep/800241?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
2,"AH Snoepgroente tomaat, tomatenmix en komkomme...",2 stuks 50% 1 stuk 35%,https://www.ah.nl/bonus/groep/800243?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1838...,15 jun,21 jun
3,Alle AH Gekoelde bakaardappelen 600 gram,voor 0.89,https://www.ah.nl/bonus/groep/791852?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,15 jun,21 jun
4,AH Sweet Palermo rode puntpaprika 2 stuks,30% korting,https://www.ah.nl/bonus/groep/800242?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_586776636...,15 jun,21 jun
...,...,...,...,...,...,...,...
182,Grill Guru Houtskool 10 kilo,voor 18.95,https://www.ah.nl/bonus/groep/779602?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,15 jun,21 jun
183,Grill Guru BBQ accessoires,25% korting,https://www.ah.nl/bonus/groep/779606?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,15 jun,21 jun
184,WK Oranje accessoires,Bonus,https://www.ah.nl/bonus/groep/794267?week=25,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1777...,15 jun,21 jun
185,AH Ridderspoor,voor 3.50,https://www.ah.nl/bonus/groep/799709?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_566634616...,15 jun,21 jun
186,Zomerdeals,Bonus,https://www.ah.nl/bonus/groep/800531?week=25,Albertijn,https://static.ah.nl/dam/product/AHI_68736b373...,15 jun,21 jun

In [13]:
df_new.to_json('../../data/AH_cleaned_8.json', orient='records', indent=4, force_ascii=False)