In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../scraping/new_raw_deals.json")

In [3]:
df

,product,discount,link,store,date,image_url
0,AH Witlof zak 4 stuks,[Klikbaar: AH Witlof zak 4 stuks uitgelicht vo...,https://www.ah.nl/bonus/groep/797007?week=22,Albertijn,26 t/m 31 mei,https://static.ah.nl/dam/product/AHI_435452393...
1,AH Verspakketten top 5,[Klikbaar: AH Verspakketten top 5 1+1 gratis],https://www.ah.nl/bonus/groep/787269?week=22,Albertijn,26 t/m 31 mei,https://static.ah.nl/mam/bonus/COMBIBEELD_1727...
2,AH Paprikamix 3 stuks,[Klikbaar: AH Paprikamix 3 stuks 2 voor 2.99],https://www.ah.nl/bonus/groep/797008?week=22,Albertijn,26 t/m 31 mei,https://static.ah.nl/dam/product/AHI_435452393...
3,AH Biologisch komkommer,[Klikbaar: AH Biologisch komkommer 30% korting],https://www.ah.nl/bonus/groep/797011?week=22,Albertijn,26 t/m 31 mei,https://static.ah.nl/dam/product/AHI_435452373...
4,AH Romaatjes 250 gram,[Klikbaar: AH Romaatjes 250 gram 1+1 gratis],https://www.ah.nl/bonus/groep/797014?week=22,Albertijn,26 t/m 31 mei,https://static.ah.nl/dam/product/AHI_4e3453413...
...,...,...,...,...,...,...
208,Elnett haarlak,[Klikbaar: Elnett haarlak Bijv. Elnett Haarlak...,https://www.ah.nl/bonus/groep/-21650?week=22,Albertijn,26 t/m 31 mei,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
209,Drs. Leenarts,[Klikbaar: Drs. Leenarts Bijv. Drs. Leenarts D...,https://www.ah.nl/bonus/groep/-21649?week=22,Albertijn,26 t/m 31 mei,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
210,Dr. van der Hoog,[Klikbaar: Dr. van der Hoog Bijv. Dr. van der ...,https://www.ah.nl/bonus/groep/-21648?week=22,Albertijn,26 t/m 31 mei,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
211,Biodermal gezichtsverzorging,[Klikbaar: Biodermal gezichtsverzorging Bijv. ...,https://www.ah.nl/bonus/groep/-21643?week=22,Albertijn,26 t/m 31 mei,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
212,Australian Gold Instant bronzer,[Klikbaar: Australian Gold Instant bronzer Bij...,https://www.ah.nl/bonus/groep/-21642?week=22,Albertijn,26 t/m 31 mei,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...

In [4]:
df["date"] = df["date"].str.replace(" t/m ", " ")
df["date"]
def date_fixer(df):
    date = df["date"].str.split(expand=True)
    start = date[0]
    end = date[1]
    month = date[2]
    start_date = start + " " + month
    end_date = end + " " + month
    df["start_date"] = start_date
    df["end_date"] = end_date
    return df

df = date_fixer(df)
df = df.drop("date", axis=1)
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Witlof zak 4 stuks,[Klikbaar: AH Witlof zak 4 stuks uitgelicht vo...,https://www.ah.nl/bonus/groep/797007?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
1,AH Verspakketten top 5,[Klikbaar: AH Verspakketten top 5 1+1 gratis],https://www.ah.nl/bonus/groep/787269?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1727...,26 mei,31 mei
2,AH Paprikamix 3 stuks,[Klikbaar: AH Paprikamix 3 stuks 2 voor 2.99],https://www.ah.nl/bonus/groep/797008?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
3,AH Biologisch komkommer,[Klikbaar: AH Biologisch komkommer 30% korting],https://www.ah.nl/bonus/groep/797011?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452373...,26 mei,31 mei
4,AH Romaatjes 250 gram,[Klikbaar: AH Romaatjes 250 gram 1+1 gratis],https://www.ah.nl/bonus/groep/797014?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4e3453413...,26 mei,31 mei
...,...,...,...,...,...,...,...
208,Elnett haarlak,[Klikbaar: Elnett haarlak Bijv. Elnett Haarlak...,https://www.ah.nl/bonus/groep/-21650?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
209,Drs. Leenarts,[Klikbaar: Drs. Leenarts Bijv. Drs. Leenarts D...,https://www.ah.nl/bonus/groep/-21649?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
210,Dr. van der Hoog,[Klikbaar: Dr. van der Hoog Bijv. Dr. van der ...,https://www.ah.nl/bonus/groep/-21648?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
211,Biodermal gezichtsverzorging,[Klikbaar: Biodermal gezichtsverzorging Bijv. ...,https://www.ah.nl/bonus/groep/-21643?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
212,Australian Gold Instant bronzer,[Klikbaar: Australian Gold Instant bronzer Bij...,https://www.ah.nl/bonus/groep/-21642?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei

In [5]:
df["discount"] = df["discount"].str[0]
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Witlof zak 4 stuks,Klikbaar: AH Witlof zak 4 stuks uitgelicht voo...,https://www.ah.nl/bonus/groep/797007?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
1,AH Verspakketten top 5,Klikbaar: AH Verspakketten top 5 1+1 gratis,https://www.ah.nl/bonus/groep/787269?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1727...,26 mei,31 mei
2,AH Paprikamix 3 stuks,Klikbaar: AH Paprikamix 3 stuks 2 voor 2.99,https://www.ah.nl/bonus/groep/797008?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
3,AH Biologisch komkommer,Klikbaar: AH Biologisch komkommer 30% korting,https://www.ah.nl/bonus/groep/797011?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452373...,26 mei,31 mei
4,AH Romaatjes 250 gram,Klikbaar: AH Romaatjes 250 gram 1+1 gratis,https://www.ah.nl/bonus/groep/797014?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4e3453413...,26 mei,31 mei
...,...,...,...,...,...,...,...
208,Elnett haarlak,Klikbaar: Elnett haarlak Bijv. Elnett Haarlak ...,https://www.ah.nl/bonus/groep/-21650?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
209,Drs. Leenarts,Klikbaar: Drs. Leenarts Bijv. Drs. Leenarts Da...,https://www.ah.nl/bonus/groep/-21649?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
210,Dr. van der Hoog,Klikbaar: Dr. van der Hoog Bijv. Dr. van der H...,https://www.ah.nl/bonus/groep/-21648?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
211,Biodermal gezichtsverzorging,Klikbaar: Biodermal gezichtsverzorging Bijv. B...,https://www.ah.nl/bonus/groep/-21643?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
212,Australian Gold Instant bronzer,Klikbaar: Australian Gold Instant bronzer Bijv...,https://www.ah.nl/bonus/groep/-21642?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei

In [6]:
df["discount"] = df["discount"].str.split(":")
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Witlof zak 4 stuks,"[Klikbaar, AH Witlof zak 4 stuks uitgelicht v...",https://www.ah.nl/bonus/groep/797007?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
1,AH Verspakketten top 5,"[Klikbaar, AH Verspakketten top 5 1+1 gratis]",https://www.ah.nl/bonus/groep/787269?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1727...,26 mei,31 mei
2,AH Paprikamix 3 stuks,"[Klikbaar, AH Paprikamix 3 stuks 2 voor 2.99]",https://www.ah.nl/bonus/groep/797008?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
3,AH Biologisch komkommer,"[Klikbaar, AH Biologisch komkommer 30% korting]",https://www.ah.nl/bonus/groep/797011?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452373...,26 mei,31 mei
4,AH Romaatjes 250 gram,"[Klikbaar, AH Romaatjes 250 gram 1+1 gratis]",https://www.ah.nl/bonus/groep/797014?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4e3453413...,26 mei,31 mei
...,...,...,...,...,...,...,...
208,Elnett haarlak,"[Klikbaar, Elnett haarlak Bijv. Elnett Haarla...",https://www.ah.nl/bonus/groep/-21650?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
209,Drs. Leenarts,"[Klikbaar, Drs. Leenarts Bijv. Drs. Leenarts ...",https://www.ah.nl/bonus/groep/-21649?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
210,Dr. van der Hoog,"[Klikbaar, Dr. van der Hoog Bijv. Dr. van der...",https://www.ah.nl/bonus/groep/-21648?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
211,Biodermal gezichtsverzorging,"[Klikbaar, Biodermal gezichtsverzorging Bijv....",https://www.ah.nl/bonus/groep/-21643?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
212,Australian Gold Instant bronzer,"[Klikbaar, Australian Gold Instant bronzer Bi...",https://www.ah.nl/bonus/groep/-21642?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei

In [7]:
df["discount"] = df["discount"].str[1]
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Witlof zak 4 stuks,AH Witlof zak 4 stuks uitgelicht voor 1.49,https://www.ah.nl/bonus/groep/797007?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
1,AH Verspakketten top 5,AH Verspakketten top 5 1+1 gratis,https://www.ah.nl/bonus/groep/787269?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1727...,26 mei,31 mei
2,AH Paprikamix 3 stuks,AH Paprikamix 3 stuks 2 voor 2.99,https://www.ah.nl/bonus/groep/797008?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
3,AH Biologisch komkommer,AH Biologisch komkommer 30% korting,https://www.ah.nl/bonus/groep/797011?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452373...,26 mei,31 mei
4,AH Romaatjes 250 gram,AH Romaatjes 250 gram 1+1 gratis,https://www.ah.nl/bonus/groep/797014?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4e3453413...,26 mei,31 mei
...,...,...,...,...,...,...,...
208,Elnett haarlak,Elnett haarlak Bijv. Elnett Haarlak extra ste...,https://www.ah.nl/bonus/groep/-21650?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
209,Drs. Leenarts,Drs. Leenarts Bijv. Drs. Leenarts Dag & nacht...,https://www.ah.nl/bonus/groep/-21649?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
210,Dr. van der Hoog,Dr. van der Hoog Bijv. Dr. van der Hoog Crème...,https://www.ah.nl/bonus/groep/-21648?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
211,Biodermal gezichtsverzorging,Biodermal gezichtsverzorging Bijv. Biodermal ...,https://www.ah.nl/bonus/groep/-21643?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
212,Australian Gold Instant bronzer,Australian Gold Instant bronzer Bijv. Austral...,https://www.ah.nl/bonus/groep/-21642?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei

In [8]:
#Deleting all rows which have bezorging.
df = df[~df["product"].str.contains("bezorging", case=False, na=False)]
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Witlof zak 4 stuks,AH Witlof zak 4 stuks uitgelicht voor 1.49,https://www.ah.nl/bonus/groep/797007?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
1,AH Verspakketten top 5,AH Verspakketten top 5 1+1 gratis,https://www.ah.nl/bonus/groep/787269?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1727...,26 mei,31 mei
2,AH Paprikamix 3 stuks,AH Paprikamix 3 stuks 2 voor 2.99,https://www.ah.nl/bonus/groep/797008?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
3,AH Biologisch komkommer,AH Biologisch komkommer 30% korting,https://www.ah.nl/bonus/groep/797011?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452373...,26 mei,31 mei
4,AH Romaatjes 250 gram,AH Romaatjes 250 gram 1+1 gratis,https://www.ah.nl/bonus/groep/797014?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4e3453413...,26 mei,31 mei
...,...,...,...,...,...,...,...
208,Elnett haarlak,Elnett haarlak Bijv. Elnett Haarlak extra ste...,https://www.ah.nl/bonus/groep/-21650?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
209,Drs. Leenarts,Drs. Leenarts Bijv. Drs. Leenarts Dag & nacht...,https://www.ah.nl/bonus/groep/-21649?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
210,Dr. van der Hoog,Dr. van der Hoog Bijv. Dr. van der Hoog Crème...,https://www.ah.nl/bonus/groep/-21648?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
211,Biodermal gezichtsverzorging,Biodermal gezichtsverzorging Bijv. Biodermal ...,https://www.ah.nl/bonus/groep/-21643?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
212,Australian Gold Instant bronzer,Australian Gold Instant bronzer Bijv. Austral...,https://www.ah.nl/bonus/groep/-21642?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei

In [9]:
df = df[~df["product"].str.contains("Online", case=True, na=False)]
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Witlof zak 4 stuks,AH Witlof zak 4 stuks uitgelicht voor 1.49,https://www.ah.nl/bonus/groep/797007?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
1,AH Verspakketten top 5,AH Verspakketten top 5 1+1 gratis,https://www.ah.nl/bonus/groep/787269?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1727...,26 mei,31 mei
2,AH Paprikamix 3 stuks,AH Paprikamix 3 stuks 2 voor 2.99,https://www.ah.nl/bonus/groep/797008?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
3,AH Biologisch komkommer,AH Biologisch komkommer 30% korting,https://www.ah.nl/bonus/groep/797011?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452373...,26 mei,31 mei
4,AH Romaatjes 250 gram,AH Romaatjes 250 gram 1+1 gratis,https://www.ah.nl/bonus/groep/797014?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4e3453413...,26 mei,31 mei
...,...,...,...,...,...,...,...
208,Elnett haarlak,Elnett haarlak Bijv. Elnett Haarlak extra ste...,https://www.ah.nl/bonus/groep/-21650?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
209,Drs. Leenarts,Drs. Leenarts Bijv. Drs. Leenarts Dag & nacht...,https://www.ah.nl/bonus/groep/-21649?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
210,Dr. van der Hoog,Dr. van der Hoog Bijv. Dr. van der Hoog Crème...,https://www.ah.nl/bonus/groep/-21648?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
211,Biodermal gezichtsverzorging,Biodermal gezichtsverzorging Bijv. Biodermal ...,https://www.ah.nl/bonus/groep/-21643?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei
212,Australian Gold Instant bronzer,Australian Gold Instant bronzer Bijv. Austral...,https://www.ah.nl/bonus/groep/-21642?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,26 mei,31 mei

In [10]:
#Removing all products which are online
target_index = df[df["product"].str.contains("OP=OP", case=True, na=False)].index[0]
df = df.loc[:target_index - 1]
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Witlof zak 4 stuks,AH Witlof zak 4 stuks uitgelicht voor 1.49,https://www.ah.nl/bonus/groep/797007?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
1,AH Verspakketten top 5,AH Verspakketten top 5 1+1 gratis,https://www.ah.nl/bonus/groep/787269?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1727...,26 mei,31 mei
2,AH Paprikamix 3 stuks,AH Paprikamix 3 stuks 2 voor 2.99,https://www.ah.nl/bonus/groep/797008?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
3,AH Biologisch komkommer,AH Biologisch komkommer 30% korting,https://www.ah.nl/bonus/groep/797011?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452373...,26 mei,31 mei
4,AH Romaatjes 250 gram,AH Romaatjes 250 gram 1+1 gratis,https://www.ah.nl/bonus/groep/797014?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4e3453413...,26 mei,31 mei
...,...,...,...,...,...,...,...
142,Grill Guru Houtskool 10 kilo,Grill Guru Houtskool 10 kilo voor 18.95,https://www.ah.nl/bonus/groep/779602?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,26 mei,31 mei
143,Grill Guru BBQ accessoires,Grill Guru BBQ accessoires 25% korting,https://www.ah.nl/bonus/groep/779606?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,26 mei,31 mei
144,SPR Noodradio,SPR Noodradio voor 34.99 Alleen in de winkel,https://www.ah.nl/bonus/groep/791153?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4579374e6...,26 mei,31 mei
145,Tefal Selection waterkoker,Tefal Selection waterkoker voor 49.99 Alleen ...,https://www.ah.nl/bonus/groep/791159?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_7269616a7...,26 mei,31 mei
146,AH Perkplant in terraspot,AH Perkplant in terraspot €2 korting Alleen i...,https://www.ah.nl/bonus/groep/791261?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1766...,26 mei,31 mei

In [11]:
def discount_name_cleaner(row):
    discount = str(row["discount"])
    product = str(row["product"])
    if(product in discount):
        return discount.replace(product, "").strip()
    return discount

df_new = df.copy()
df_new["discount"] = df_new.apply(discount_name_cleaner, axis=1)
df_new

,product,discount,link,store,image_url,start_date,end_date
0,AH Witlof zak 4 stuks,uitgelicht voor 1.49,https://www.ah.nl/bonus/groep/797007?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
1,AH Verspakketten top 5,1+1 gratis,https://www.ah.nl/bonus/groep/787269?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1727...,26 mei,31 mei
2,AH Paprikamix 3 stuks,2 voor 2.99,https://www.ah.nl/bonus/groep/797008?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
3,AH Biologisch komkommer,30% korting,https://www.ah.nl/bonus/groep/797011?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452373...,26 mei,31 mei
4,AH Romaatjes 250 gram,1+1 gratis,https://www.ah.nl/bonus/groep/797014?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4e3453413...,26 mei,31 mei
...,...,...,...,...,...,...,...
142,Grill Guru Houtskool 10 kilo,voor 18.95,https://www.ah.nl/bonus/groep/779602?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,26 mei,31 mei
143,Grill Guru BBQ accessoires,25% korting,https://www.ah.nl/bonus/groep/779606?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,26 mei,31 mei
144,SPR Noodradio,voor 34.99 Alleen in de winkel,https://www.ah.nl/bonus/groep/791153?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4579374e6...,26 mei,31 mei
145,Tefal Selection waterkoker,voor 49.99 Alleen in de winkel,https://www.ah.nl/bonus/groep/791159?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_7269616a7...,26 mei,31 mei
146,AH Perkplant in terraspot,€2 korting Alleen in de winkel van 8 voor 6,https://www.ah.nl/bonus/groep/791261?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1766...,26 mei,31 mei

In [12]:
#removing Allen in winkel
def winkel(text):
    wink = "Alleen in de winkel"
    if wink in text:
        return text.replace(wink, "").strip()
    return text
df_new["discount"] = df_new["discount"].apply(winkel)
df_new

,product,discount,link,store,image_url,start_date,end_date
0,AH Witlof zak 4 stuks,uitgelicht voor 1.49,https://www.ah.nl/bonus/groep/797007?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
1,AH Verspakketten top 5,1+1 gratis,https://www.ah.nl/bonus/groep/787269?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1727...,26 mei,31 mei
2,AH Paprikamix 3 stuks,2 voor 2.99,https://www.ah.nl/bonus/groep/797008?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452393...,26 mei,31 mei
3,AH Biologisch komkommer,30% korting,https://www.ah.nl/bonus/groep/797011?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452373...,26 mei,31 mei
4,AH Romaatjes 250 gram,1+1 gratis,https://www.ah.nl/bonus/groep/797014?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4e3453413...,26 mei,31 mei
...,...,...,...,...,...,...,...
142,Grill Guru Houtskool 10 kilo,voor 18.95,https://www.ah.nl/bonus/groep/779602?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,26 mei,31 mei
143,Grill Guru BBQ accessoires,25% korting,https://www.ah.nl/bonus/groep/779606?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,26 mei,31 mei
144,SPR Noodradio,voor 34.99,https://www.ah.nl/bonus/groep/791153?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_4579374e6...,26 mei,31 mei
145,Tefal Selection waterkoker,voor 49.99,https://www.ah.nl/bonus/groep/791159?week=22,Albertijn,https://static.ah.nl/dam/product/AHI_7269616a7...,26 mei,31 mei
146,AH Perkplant in terraspot,€2 korting van 8 voor 6,https://www.ah.nl/bonus/groep/791261?week=22,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1766...,26 mei,31 mei

In [13]:
df_new.to_json('../../data/AH_cleaned_5.json', orient='records', indent=4, force_ascii=False)