In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../scraping/new_raw_deals.json", convert_dates=False)

In [3]:
df

,product,discount,link,store,date,image_url
0,AH Bloemkool,[Klikbaar: AH Bloemkool Los voor 1.39],https://www.ah.nl/bonus/groep/800701?week=26,Albertijn,22 t/m 28 jun,https://static.ah.nl/dam/product/AHI_435452313...
1,AH Tasty Tom trostomaten 380 gram en avocado e...,[Klikbaar: AH Tasty Tom trostomaten 380 gram e...,https://www.ah.nl/bonus/groep/801421?week=26,Albertijn,22 t/m 28 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_1849...
2,Alle AH Italiaanse roerbakgroenten en Thaise e...,[Klikbaar: Alle AH Italiaanse roerbakgroenten ...,https://www.ah.nl/bonus/groep/794514?week=26,Albertijn,22 t/m 28 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...
3,Alle Bonduelle 255-400 gram,[Klikbaar: Alle Bonduelle 255-400 gram 2 voor ...,https://www.ah.nl/bonus/groep/794563?week=26,Albertijn,22 t/m 28 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...
4,Alle AH Ongekoelde 4-persoons verspakketten,[Klikbaar: Alle AH Ongekoelde 4-persoons versp...,https://www.ah.nl/bonus/groep/794540?week=26,Albertijn,22 t/m 28 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...
...,...,...,...,...,...,...
200,Elnett haarlak,[Klikbaar: Elnett haarlak Bijv. Elnett Haarlak...,https://www.ah.nl/bonus/groep/-21828?week=26,Albertijn,22 t/m 28 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
201,Drs Leenarts gezichtsverzorging,[Klikbaar: Drs Leenarts gezichtsverzorging Bij...,https://www.ah.nl/bonus/groep/-21826?week=26,Albertijn,22 t/m 28 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
202,Dermolin,[Klikbaar: Dermolin Bijv. Dermolin Shampoo - 2...,https://www.ah.nl/bonus/groep/-21825?week=26,Albertijn,22 t/m 28 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
203,Biodermal,[Klikbaar: Biodermal Bijv. Biodermal P-CL-E ha...,https://www.ah.nl/bonus/groep/-21822?week=26,Albertijn,22 t/m 28 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...
204,Australian Gold Instant bronzer spray,[Klikbaar: Australian Gold Instant bronzer spr...,https://www.ah.nl/bonus/groep/-21820?week=26,Albertijn,22 t/m 28 jun,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...

In [4]:
df["date"] = df["date"].str.replace(" t/m ", " ")
df["date"]
def date_fixer(df):
    date = df["date"].str.split(expand=True)
    start = date[0]
    end = date[1]
    month = date[2]
    start_date = start + " " + month
    end_date = end + " " + month
    df["start_date"] = start_date
    df["end_date"] = end_date
    return df

df = date_fixer(df)
df = df.drop("date", axis=1)
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Bloemkool,[Klikbaar: AH Bloemkool Los voor 1.39],https://www.ah.nl/bonus/groep/800701?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
1,AH Tasty Tom trostomaten 380 gram en avocado e...,[Klikbaar: AH Tasty Tom trostomaten 380 gram e...,https://www.ah.nl/bonus/groep/801421?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1849...,22 jun,28 jun
2,Alle AH Italiaanse roerbakgroenten en Thaise e...,[Klikbaar: Alle AH Italiaanse roerbakgroenten ...,https://www.ah.nl/bonus/groep/794514?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
3,Alle Bonduelle 255-400 gram,[Klikbaar: Alle Bonduelle 255-400 gram 2 voor ...,https://www.ah.nl/bonus/groep/794563?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
4,Alle AH Ongekoelde 4-persoons verspakketten,[Klikbaar: Alle AH Ongekoelde 4-persoons versp...,https://www.ah.nl/bonus/groep/794540?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
...,...,...,...,...,...,...,...
200,Elnett haarlak,[Klikbaar: Elnett haarlak Bijv. Elnett Haarlak...,https://www.ah.nl/bonus/groep/-21828?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
201,Drs Leenarts gezichtsverzorging,[Klikbaar: Drs Leenarts gezichtsverzorging Bij...,https://www.ah.nl/bonus/groep/-21826?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
202,Dermolin,[Klikbaar: Dermolin Bijv. Dermolin Shampoo - 2...,https://www.ah.nl/bonus/groep/-21825?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
203,Biodermal,[Klikbaar: Biodermal Bijv. Biodermal P-CL-E ha...,https://www.ah.nl/bonus/groep/-21822?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
204,Australian Gold Instant bronzer spray,[Klikbaar: Australian Gold Instant bronzer spr...,https://www.ah.nl/bonus/groep/-21820?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun

In [5]:
df["discount"] = df["discount"].str[0]
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Bloemkool,Klikbaar: AH Bloemkool Los voor 1.39,https://www.ah.nl/bonus/groep/800701?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
1,AH Tasty Tom trostomaten 380 gram en avocado e...,Klikbaar: AH Tasty Tom trostomaten 380 gram en...,https://www.ah.nl/bonus/groep/801421?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1849...,22 jun,28 jun
2,Alle AH Italiaanse roerbakgroenten en Thaise e...,Klikbaar: Alle AH Italiaanse roerbakgroenten e...,https://www.ah.nl/bonus/groep/794514?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
3,Alle Bonduelle 255-400 gram,Klikbaar: Alle Bonduelle 255-400 gram 2 voor 2.99,https://www.ah.nl/bonus/groep/794563?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
4,Alle AH Ongekoelde 4-persoons verspakketten,Klikbaar: Alle AH Ongekoelde 4-persoons verspa...,https://www.ah.nl/bonus/groep/794540?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
...,...,...,...,...,...,...,...
200,Elnett haarlak,Klikbaar: Elnett haarlak Bijv. Elnett Haarlak ...,https://www.ah.nl/bonus/groep/-21828?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
201,Drs Leenarts gezichtsverzorging,Klikbaar: Drs Leenarts gezichtsverzorging Bijv...,https://www.ah.nl/bonus/groep/-21826?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
202,Dermolin,Klikbaar: Dermolin Bijv. Dermolin Shampoo - 2 ...,https://www.ah.nl/bonus/groep/-21825?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
203,Biodermal,Klikbaar: Biodermal Bijv. Biodermal P-CL-E han...,https://www.ah.nl/bonus/groep/-21822?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
204,Australian Gold Instant bronzer spray,Klikbaar: Australian Gold Instant bronzer spra...,https://www.ah.nl/bonus/groep/-21820?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun

In [6]:
df["discount"] = df["discount"].str.split(":")
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Bloemkool,"[Klikbaar, AH Bloemkool Los voor 1.39]",https://www.ah.nl/bonus/groep/800701?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
1,AH Tasty Tom trostomaten 380 gram en avocado e...,"[Klikbaar, AH Tasty Tom trostomaten 380 gram ...",https://www.ah.nl/bonus/groep/801421?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1849...,22 jun,28 jun
2,Alle AH Italiaanse roerbakgroenten en Thaise e...,"[Klikbaar, Alle AH Italiaanse roerbakgroenten...",https://www.ah.nl/bonus/groep/794514?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
3,Alle Bonduelle 255-400 gram,"[Klikbaar, Alle Bonduelle 255-400 gram 2 voor...",https://www.ah.nl/bonus/groep/794563?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
4,Alle AH Ongekoelde 4-persoons verspakketten,"[Klikbaar, Alle AH Ongekoelde 4-persoons vers...",https://www.ah.nl/bonus/groep/794540?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
...,...,...,...,...,...,...,...
200,Elnett haarlak,"[Klikbaar, Elnett haarlak Bijv. Elnett Haarla...",https://www.ah.nl/bonus/groep/-21828?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
201,Drs Leenarts gezichtsverzorging,"[Klikbaar, Drs Leenarts gezichtsverzorging Bi...",https://www.ah.nl/bonus/groep/-21826?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
202,Dermolin,"[Klikbaar, Dermolin Bijv. Dermolin Shampoo - ...",https://www.ah.nl/bonus/groep/-21825?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
203,Biodermal,"[Klikbaar, Biodermal Bijv. Biodermal P-CL-E h...",https://www.ah.nl/bonus/groep/-21822?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
204,Australian Gold Instant bronzer spray,"[Klikbaar, Australian Gold Instant bronzer sp...",https://www.ah.nl/bonus/groep/-21820?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun

In [7]:
df["discount"] = df["discount"].str[1]
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Bloemkool,AH Bloemkool Los voor 1.39,https://www.ah.nl/bonus/groep/800701?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
1,AH Tasty Tom trostomaten 380 gram en avocado e...,AH Tasty Tom trostomaten 380 gram en avocado ...,https://www.ah.nl/bonus/groep/801421?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1849...,22 jun,28 jun
2,Alle AH Italiaanse roerbakgroenten en Thaise e...,Alle AH Italiaanse roerbakgroenten en Thaise ...,https://www.ah.nl/bonus/groep/794514?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
3,Alle Bonduelle 255-400 gram,Alle Bonduelle 255-400 gram 2 voor 2.99,https://www.ah.nl/bonus/groep/794563?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
4,Alle AH Ongekoelde 4-persoons verspakketten,Alle AH Ongekoelde 4-persoons verspakketten v...,https://www.ah.nl/bonus/groep/794540?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
...,...,...,...,...,...,...,...
200,Elnett haarlak,Elnett haarlak Bijv. Elnett Haarlak extra ste...,https://www.ah.nl/bonus/groep/-21828?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
201,Drs Leenarts gezichtsverzorging,Drs Leenarts gezichtsverzorging Bijv. Drs. Le...,https://www.ah.nl/bonus/groep/-21826?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
202,Dermolin,Dermolin Bijv. Dermolin Shampoo - 2 x 200 ml ...,https://www.ah.nl/bonus/groep/-21825?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
203,Biodermal,Biodermal Bijv. Biodermal P-CL-E handcreme - ...,https://www.ah.nl/bonus/groep/-21822?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
204,Australian Gold Instant bronzer spray,Australian Gold Instant bronzer spray Bijv. A...,https://www.ah.nl/bonus/groep/-21820?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun

In [8]:
#Deleting all rows which have bezorging.
df = df[~df["product"].str.contains("bezorging", case=False, na=False)]
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Bloemkool,AH Bloemkool Los voor 1.39,https://www.ah.nl/bonus/groep/800701?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
1,AH Tasty Tom trostomaten 380 gram en avocado e...,AH Tasty Tom trostomaten 380 gram en avocado ...,https://www.ah.nl/bonus/groep/801421?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1849...,22 jun,28 jun
2,Alle AH Italiaanse roerbakgroenten en Thaise e...,Alle AH Italiaanse roerbakgroenten en Thaise ...,https://www.ah.nl/bonus/groep/794514?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
3,Alle Bonduelle 255-400 gram,Alle Bonduelle 255-400 gram 2 voor 2.99,https://www.ah.nl/bonus/groep/794563?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
4,Alle AH Ongekoelde 4-persoons verspakketten,Alle AH Ongekoelde 4-persoons verspakketten v...,https://www.ah.nl/bonus/groep/794540?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
...,...,...,...,...,...,...,...
200,Elnett haarlak,Elnett haarlak Bijv. Elnett Haarlak extra ste...,https://www.ah.nl/bonus/groep/-21828?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
201,Drs Leenarts gezichtsverzorging,Drs Leenarts gezichtsverzorging Bijv. Drs. Le...,https://www.ah.nl/bonus/groep/-21826?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
202,Dermolin,Dermolin Bijv. Dermolin Shampoo - 2 x 200 ml ...,https://www.ah.nl/bonus/groep/-21825?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
203,Biodermal,Biodermal Bijv. Biodermal P-CL-E handcreme - ...,https://www.ah.nl/bonus/groep/-21822?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
204,Australian Gold Instant bronzer spray,Australian Gold Instant bronzer spray Bijv. A...,https://www.ah.nl/bonus/groep/-21820?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun

In [9]:
df = df[~df["product"].str.contains("Online", case=True, na=False)]
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Bloemkool,AH Bloemkool Los voor 1.39,https://www.ah.nl/bonus/groep/800701?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
1,AH Tasty Tom trostomaten 380 gram en avocado e...,AH Tasty Tom trostomaten 380 gram en avocado ...,https://www.ah.nl/bonus/groep/801421?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1849...,22 jun,28 jun
2,Alle AH Italiaanse roerbakgroenten en Thaise e...,Alle AH Italiaanse roerbakgroenten en Thaise ...,https://www.ah.nl/bonus/groep/794514?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
3,Alle Bonduelle 255-400 gram,Alle Bonduelle 255-400 gram 2 voor 2.99,https://www.ah.nl/bonus/groep/794563?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
4,Alle AH Ongekoelde 4-persoons verspakketten,Alle AH Ongekoelde 4-persoons verspakketten v...,https://www.ah.nl/bonus/groep/794540?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
...,...,...,...,...,...,...,...
200,Elnett haarlak,Elnett haarlak Bijv. Elnett Haarlak extra ste...,https://www.ah.nl/bonus/groep/-21828?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
201,Drs Leenarts gezichtsverzorging,Drs Leenarts gezichtsverzorging Bijv. Drs. Le...,https://www.ah.nl/bonus/groep/-21826?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
202,Dermolin,Dermolin Bijv. Dermolin Shampoo - 2 x 200 ml ...,https://www.ah.nl/bonus/groep/-21825?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
203,Biodermal,Biodermal Bijv. Biodermal P-CL-E handcreme - ...,https://www.ah.nl/bonus/groep/-21822?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun
204,Australian Gold Instant bronzer spray,Australian Gold Instant bronzer spray Bijv. A...,https://www.ah.nl/bonus/groep/-21820?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_OO-2...,22 jun,28 jun

In [10]:
#Removing all products which are online
target_index = df[df["product"].str.contains("OP=OP", case=True, na=False)].index[0]
df = df.loc[:target_index - 1]
df

,product,discount,link,store,image_url,start_date,end_date
0,AH Bloemkool,AH Bloemkool Los voor 1.39,https://www.ah.nl/bonus/groep/800701?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
1,AH Tasty Tom trostomaten 380 gram en avocado e...,AH Tasty Tom trostomaten 380 gram en avocado ...,https://www.ah.nl/bonus/groep/801421?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1849...,22 jun,28 jun
2,Alle AH Italiaanse roerbakgroenten en Thaise e...,Alle AH Italiaanse roerbakgroenten en Thaise ...,https://www.ah.nl/bonus/groep/794514?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
3,Alle Bonduelle 255-400 gram,Alle Bonduelle 255-400 gram 2 voor 2.99,https://www.ah.nl/bonus/groep/794563?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
4,Alle AH Ongekoelde 4-persoons verspakketten,Alle AH Ongekoelde 4-persoons verspakketten v...,https://www.ah.nl/bonus/groep/794540?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
...,...,...,...,...,...,...,...
138,Weber BBQ accessoires,Weber BBQ accessoires Bonus,https://www.ah.nl/bonus/groep/779600?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_4b5068594...,22 jun,28 jun
139,Grill Guru BBQ accessoires,Grill Guru BBQ accessoires 25% korting,https://www.ah.nl/bonus/groep/779606?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
140,WK Oranje accessoires,WK Oranje accessoires Bonus,https://www.ah.nl/bonus/groep/794267?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1777...,22 jun,28 jun
141,Toverland,Toverland Bonus,https://www.ah.nl/bonus/groep/800529?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_497a6e695...,22 jun,28 jun
142,Zomerdeals,Zomerdeals Bonus,https://www.ah.nl/bonus/groep/800531?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_68736b373...,22 jun,28 jun

In [11]:
def discount_name_cleaner(row):
    discount = str(row["discount"])
    product = str(row["product"])
    if(product in discount):
        return discount.replace(product, "").strip()
    return discount

df_new = df.copy()
df_new["discount"] = df_new.apply(discount_name_cleaner, axis=1)
df_new

,product,discount,link,store,image_url,start_date,end_date
0,AH Bloemkool,Los voor 1.39,https://www.ah.nl/bonus/groep/800701?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
1,AH Tasty Tom trostomaten 380 gram en avocado e...,1+1 gratis,https://www.ah.nl/bonus/groep/801421?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1849...,22 jun,28 jun
2,Alle AH Italiaanse roerbakgroenten en Thaise e...,1+1 gratis,https://www.ah.nl/bonus/groep/794514?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
3,Alle Bonduelle 255-400 gram,2 voor 2.99,https://www.ah.nl/bonus/groep/794563?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
4,Alle AH Ongekoelde 4-persoons verspakketten,voor 4.49,https://www.ah.nl/bonus/groep/794540?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
...,...,...,...,...,...,...,...
138,Weber BBQ accessoires,Bonus,https://www.ah.nl/bonus/groep/779600?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_4b5068594...,22 jun,28 jun
139,Grill Guru BBQ accessoires,25% korting,https://www.ah.nl/bonus/groep/779606?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
140,WK Oranje accessoires,Bonus,https://www.ah.nl/bonus/groep/794267?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1777...,22 jun,28 jun
141,Toverland,Bonus,https://www.ah.nl/bonus/groep/800529?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_497a6e695...,22 jun,28 jun
142,Zomerdeals,Bonus,https://www.ah.nl/bonus/groep/800531?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_68736b373...,22 jun,28 jun

In [12]:
#removing Allen in winkel
def winkel(text):
    wink = "Alleen in de winkel"
    if wink in text:
        return text.replace(wink, "").strip()
    return text
df_new["discount"] = df_new["discount"].apply(winkel)
df_new

,product,discount,link,store,image_url,start_date,end_date
0,AH Bloemkool,Los voor 1.39,https://www.ah.nl/bonus/groep/800701?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
1,AH Tasty Tom trostomaten 380 gram en avocado e...,1+1 gratis,https://www.ah.nl/bonus/groep/801421?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1849...,22 jun,28 jun
2,Alle AH Italiaanse roerbakgroenten en Thaise e...,1+1 gratis,https://www.ah.nl/bonus/groep/794514?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
3,Alle Bonduelle 255-400 gram,2 voor 2.99,https://www.ah.nl/bonus/groep/794563?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
4,Alle AH Ongekoelde 4-persoons verspakketten,voor 4.49,https://www.ah.nl/bonus/groep/794540?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1780...,22 jun,28 jun
...,...,...,...,...,...,...,...
138,Weber BBQ accessoires,Bonus,https://www.ah.nl/bonus/groep/779600?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_4b5068594...,22 jun,28 jun
139,Grill Guru BBQ accessoires,25% korting,https://www.ah.nl/bonus/groep/779606?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_435452313...,22 jun,28 jun
140,WK Oranje accessoires,Bonus,https://www.ah.nl/bonus/groep/794267?week=26,Albertijn,https://static.ah.nl/mam/bonus/COMBIBEELD_1777...,22 jun,28 jun
141,Toverland,Bonus,https://www.ah.nl/bonus/groep/800529?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_497a6e695...,22 jun,28 jun
142,Zomerdeals,Bonus,https://www.ah.nl/bonus/groep/800531?week=26,Albertijn,https://static.ah.nl/dam/product/AHI_68736b373...,22 jun,28 jun

In [13]:
df_new.to_json('../../data/AH_cleaned_9.json', orient='records', indent=4, force_ascii=False)