In [2]:
import pandas as pd

In [3]:
df = pd.read_json("../scraping/new_raw_deals.json")

In [4]:
df

,product,discount,link,store,date
0,Alle Hak*,[Klikbaar: Alle Hak* *M.u.v. taart & vlaaifrui...,https://www.ah.nl/bonus/groep/782667?week=19,Albertijn,4 t/m 10 mei
1,AH Courgette,[Klikbaar: AH Courgette 2 voor 1.49],https://www.ah.nl/bonus/groep/790782?week=19,Albertijn,4 t/m 10 mei
2,AH Prei,[Klikbaar: AH Prei 2 voor 0.89],https://www.ah.nl/bonus/groep/790780?week=19,Albertijn,4 t/m 10 mei
3,AH Iets kruimige aardappel 3 kilo,[Klikbaar: AH Iets kruimige aardappel 3 kilo 2...,https://www.ah.nl/bonus/groep/790779?week=19,Albertijn,4 t/m 10 mei
4,Alle AH Roerbakgroenten 400 gram,[Klikbaar: Alle AH Roerbakgroenten 400 gram 2 ...,https://www.ah.nl/bonus/groep/782698?week=19,Albertijn,4 t/m 10 mei
...,...,...,...,...,...
193,Gillette Mach 3 scheersysteem turbo 2,[Klikbaar: Gillette Mach 3 scheersysteem turbo...,https://www.ah.nl/bonus/groep/-21601?week=19,Albertijn,4 t/m 10 mei
194,Garnier gezichtsverzorging,[Klikbaar: Garnier gezichtsverzorging Bijv. Ga...,https://www.ah.nl/bonus/groep/-21600?week=19,Albertijn,4 t/m 10 mei
195,Etos tandenborstel,[Klikbaar: Etos tandenborstel 1 stuks 2e halve...,https://www.ah.nl/bonus/groep/-21597?week=19,Albertijn,4 t/m 10 mei
196,Etos gezichtsverzorging,[Klikbaar: Etos gezichtsverzorging Bijv. Etos ...,https://www.ah.nl/bonus/groep/-21591?week=19,Albertijn,4 t/m 10 mei
197,Drs Leenarts,[Klikbaar: Drs Leenarts Bijv. Drs. Leenarts Da...,https://www.ah.nl/bonus/groep/-21588?week=19,Albertijn,4 t/m 10 mei

In [5]:
df["date"] = df["date"].str.replace(" t/m ", " ")
def date_fixer(df):
    patern = r'\d+\s\w+'
    df["start_date"] = df["date"].str.findall(patern).str[0]
    df["end_date"] = df["date"].str.findall(patern).str[1]
    return df

df = date_fixer(df)
df = df.drop("date", axis = 1)

In [90]:
df["discount"] = df["discount"].str.split(":")

In [91]:
df["discount"] = df["discount"].str[1]

In [92]:
df["discount"]

0       AH Snoepgroente tomaat 500 gram 2 stuks van 6...
1       Alle AH Gekoelde aardappelen 600 gram Bijv. a...
2                      AH Avocado Los van 4.17 voor 2.99
3       AH Geschrapte worteltjes grootverpakking van ...
4       AH Buitenbeentjes Nederlandse witte asperges ...
                             ...
176     Gillette Mach 3 scheersysteem 1 stuks van 33....
177     Garnier en Bio-Oil Bijv. Garnier Skin Natural...
178     Etos gezichtsverzorging Bijv. Etos Eye make-u...
179     Elnett haarlak Bijv. Elnett Haarlak extra ste...
180     Biodermal gezichts- en bodyverzorging Bijv. B...
Name: discount, Length: 181, dtype: object

In [93]:
df["discount"] = df["discount"].str.split(",", n=1)
df["discount"] = df["discount"].str[1]
df["discount"]

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
176    NaN
177    NaN
178    NaN
179    NaN
180    NaN
Name: discount, Length: 181, dtype: object

In [94]:
#Deleting all rows which have either bezorging or online.
df = df[~df["product"].str.contains("bezorging", case=False, na=False)]

In [95]:
df = df[~df["product"].str.contains("Online", case=True, na=False)]
df

,product,discount,link,store,start_date,end_date
0,AH Snoepgroente tomaat 500 gram,NaN,https://www.ah.nl/bonus/groep/789801?week=18,Albertijn,27 apr,3 mei
1,Alle AH Gekoelde aardappelen 600 gram,NaN,https://www.ah.nl/bonus/groep/780836?week=18,Albertijn,27 apr,3 mei
2,AH Avocado,NaN,https://www.ah.nl/bonus/groep/789802?week=18,Albertijn,27 apr,3 mei
3,AH Geschrapte worteltjes grootverpakking,NaN,https://www.ah.nl/bonus/groep/780838?week=18,Albertijn,27 apr,3 mei
4,AH Buitenbeentjes Nederlandse witte asperges 7...,NaN,https://www.ah.nl/bonus/groep/789258?week=18,Albertijn,27 apr,3 mei
...,...,...,...,...,...,...
176,Gillette Mach 3 scheersysteem,NaN,https://www.ah.nl/bonus/groep/-21503?week=18,Albertijn,27 apr,3 mei
177,Garnier en Bio-Oil,NaN,https://www.ah.nl/bonus/groep/-21502?week=18,Albertijn,27 apr,3 mei
178,Etos gezichtsverzorging,NaN,https://www.ah.nl/bonus/groep/-21497?week=18,Albertijn,27 apr,3 mei
179,Elnett haarlak,NaN,https://www.ah.nl/bonus/groep/-21496?week=18,Albertijn,27 apr,3 mei
180,Biodermal gezichts- en bodyverzorging,NaN,https://www.ah.nl/bonus/groep/-21492?week=18,Albertijn,27 apr,3 mei

In [96]:
#Removing all products which are online
target_index = df[df["product"].str.contains("OP=OP", case=True, na=False)].index[0]
df = df.loc[:target_index - 1]
df

,product,discount,link,store,start_date,end_date
0,AH Snoepgroente tomaat 500 gram,NaN,https://www.ah.nl/bonus/groep/789801?week=18,Albertijn,27 apr,3 mei
1,Alle AH Gekoelde aardappelen 600 gram,NaN,https://www.ah.nl/bonus/groep/780836?week=18,Albertijn,27 apr,3 mei
2,AH Avocado,NaN,https://www.ah.nl/bonus/groep/789802?week=18,Albertijn,27 apr,3 mei
3,AH Geschrapte worteltjes grootverpakking,NaN,https://www.ah.nl/bonus/groep/780838?week=18,Albertijn,27 apr,3 mei
4,AH Buitenbeentjes Nederlandse witte asperges 7...,NaN,https://www.ah.nl/bonus/groep/789258?week=18,Albertijn,27 apr,3 mei
...,...,...,...,...,...,...
123,Grill Fanatics BBQ accessoires,NaN,https://www.ah.nl/bonus/groep/779097?week=18,Albertijn,27 apr,3 mei
124,AH BBQ accessoires,NaN,https://www.ah.nl/bonus/groep/779107?week=18,Albertijn,27 apr,3 mei
125,Weber BBQ accessoires,NaN,https://www.ah.nl/bonus/groep/779600?week=18,Albertijn,27 apr,3 mei
126,Grill Guru Houtskool 10 kilo,NaN,https://www.ah.nl/bonus/groep/779602?week=18,Albertijn,27 apr,3 mei
127,Grill Guru BBQ accessoires,NaN,https://www.ah.nl/bonus/groep/779606?week=18,Albertijn,27 apr,3 mei

In [78]:
#cleaning the remaining discount values
def discount_clean(df):
    df["product"] = df["product"].str.split(", ", expand=False)
    df["discount"] = df["discount"].str.split(", ", expand=False)
    mask = df["product"].str.len() > 1
    df.loc[mask, "discount"] = df.loc[mask, "discount"].str[1]
    return df

df_final = df.copy()
df_final = discount_clean(df_final)
df_final["product"] = df_final["product"].str.join(', ')
df_final["discount"] = df_final["discount"].apply(
    lambda x: ', '.join(x) if isinstance(x, list) else x
)
df_final

,product,discount,link,store,start_date,end_date
0,AH Aardappelpartjes Provençaals gekruid 600 gram,voor 0.99,https://www.ah.nl/bonus/groep/766837?week=9,Albertijn,23 feb,1 mrt
1,AH Geschrapte worteltjes 500 gram,2e gratis,https://www.ah.nl/bonus/groep/766809?week=9,Albertijn,23 feb,1 mrt
2,AH Rucola 85 gram,voor 0.99,https://www.ah.nl/bonus/groep/766835?week=9,Albertijn,23 feb,1 mrt
3,AH Biologisch winterpeen 750 gram en AH Biolog...,2 voor 1.99,https://www.ah.nl/bonus/groep/775045?week=9,Albertijn,23 feb,1 mrt
4,Alle AH Italiaanse verspakketten,€1 korting,https://www.ah.nl/bonus/groep/766864?week=9,Albertijn,23 feb,1 mrt
...,...,...,...,...,...,...
139,AH Aphelandra of pannenkoekenplant,"Bonus, Alleen in de winkel",https://www.ah.nl/bonus/groep/769923?week=9,Albertijn,23 feb,1 mrt
140,AH Pasen tafelaankleding,Feestfavoriet,https://www.ah.nl/bonus/groep/763668?week=9,Albertijn,23 feb,1 mrt
141,AH Paasartikelen,Feestfavoriet,https://www.ah.nl/bonus/groep/763698?week=9,Albertijn,23 feb,1 mrt
142,AH Pasen tafelversiering,Feestfavoriet,https://www.ah.nl/bonus/groep/763992?week=9,Albertijn,23 feb,1 mrt
143,Kärcher,Bonus,https://www.ah.nl/bonus/groep/773943?week=9,Albertijn,23 feb,1 mrt

In [81]:
df_final.to_json('data/AH_cleaned.json', orient='records', indent = 4, force_ascii=False)