In [12]:
import pandas as pd

In [13]:
df = pd.read_json("../scraping/new_raw_deals.json")

In [14]:
df

,product,discount,link,store,date
0,AH Nederlandse witte asperges 500 gram of groe...,[Klikbaar: AH Nederlandse witte asperges 500 g...,https://www.ah.nl/bonus/groep/794197?week=20,Albertijn,11 t/m 17 mei
1,AH Broccoli,[Klikbaar: AH Broccoli uitgelicht per 500 gram...,https://www.ah.nl/bonus/groep/794193?week=20,Albertijn,11 t/m 17 mei
2,AH Trostomaten,[Klikbaar: AH Trostomaten uitgelicht per 500 g...,https://www.ah.nl/bonus/groep/794194?week=20,Albertijn,11 t/m 17 mei
3,Alle AH Kleinverpakkingen groentegemak,[Klikbaar: Alle AH Kleinverpakkingen groentege...,https://www.ah.nl/bonus/groep/784569?week=20,Albertijn,11 t/m 17 mei
4,AH Snoepgroente tomaat 500 gram en komkommer 4...,[Klikbaar: AH Snoepgroente tomaat 500 gram en ...,https://www.ah.nl/bonus/groep/794195?week=20,Albertijn,11 t/m 17 mei
...,...,...,...,...,...
199,Gliss Serum daily oil,[Klikbaar: Gliss Serum daily oil 67 ml 1+1 gra...,https://www.ah.nl/bonus/groep/-21602?week=20,Albertijn,11 t/m 17 mei
200,Gillette Mach 3 scheersysteem turbo 2,[Klikbaar: Gillette Mach 3 scheersysteem turbo...,https://www.ah.nl/bonus/groep/-21601?week=20,Albertijn,11 t/m 17 mei
201,Etos tandenborstel,[Klikbaar: Etos tandenborstel 1 stuks 2e halve...,https://www.ah.nl/bonus/groep/-21597?week=20,Albertijn,11 t/m 17 mei
202,Etos gezichtsverzorging,[Klikbaar: Etos gezichtsverzorging Bijv. Etos ...,https://www.ah.nl/bonus/groep/-21591?week=20,Albertijn,11 t/m 17 mei
203,Drs Leenarts,[Klikbaar: Drs Leenarts Bijv. Drs. Leenarts Da...,https://www.ah.nl/bonus/groep/-21588?week=20,Albertijn,11 t/m 17 mei

In [15]:
df["date"] = df["date"].str.replace(" t/m ", " ")
df["date"]
def date_fixer(df):
    date = df["date"].str.split(expand=True)
    start = date[0]
    end = date[1]
    month = date[2]
    start_date = start + " " + month
    end_date = end + " " + month
    df["start_date"] = start_date
    df["end_date"] = end_date
    return df

df = date_fixer(df)
df = df.drop("date", axis=1)
df

,product,discount,link,store,start_date,end_date
0,AH Nederlandse witte asperges 500 gram of groe...,[Klikbaar: AH Nederlandse witte asperges 500 g...,https://www.ah.nl/bonus/groep/794197?week=20,Albertijn,11 mei,17 mei
1,AH Broccoli,[Klikbaar: AH Broccoli uitgelicht per 500 gram...,https://www.ah.nl/bonus/groep/794193?week=20,Albertijn,11 mei,17 mei
2,AH Trostomaten,[Klikbaar: AH Trostomaten uitgelicht per 500 g...,https://www.ah.nl/bonus/groep/794194?week=20,Albertijn,11 mei,17 mei
3,Alle AH Kleinverpakkingen groentegemak,[Klikbaar: Alle AH Kleinverpakkingen groentege...,https://www.ah.nl/bonus/groep/784569?week=20,Albertijn,11 mei,17 mei
4,AH Snoepgroente tomaat 500 gram en komkommer 4...,[Klikbaar: AH Snoepgroente tomaat 500 gram en ...,https://www.ah.nl/bonus/groep/794195?week=20,Albertijn,11 mei,17 mei
...,...,...,...,...,...,...
199,Gliss Serum daily oil,[Klikbaar: Gliss Serum daily oil 67 ml 1+1 gra...,https://www.ah.nl/bonus/groep/-21602?week=20,Albertijn,11 mei,17 mei
200,Gillette Mach 3 scheersysteem turbo 2,[Klikbaar: Gillette Mach 3 scheersysteem turbo...,https://www.ah.nl/bonus/groep/-21601?week=20,Albertijn,11 mei,17 mei
201,Etos tandenborstel,[Klikbaar: Etos tandenborstel 1 stuks 2e halve...,https://www.ah.nl/bonus/groep/-21597?week=20,Albertijn,11 mei,17 mei
202,Etos gezichtsverzorging,[Klikbaar: Etos gezichtsverzorging Bijv. Etos ...,https://www.ah.nl/bonus/groep/-21591?week=20,Albertijn,11 mei,17 mei
203,Drs Leenarts,[Klikbaar: Drs Leenarts Bijv. Drs. Leenarts Da...,https://www.ah.nl/bonus/groep/-21588?week=20,Albertijn,11 mei,17 mei

In [16]:
df["discount"] = df["discount"].str[0]
df

,product,discount,link,store,start_date,end_date
0,AH Nederlandse witte asperges 500 gram of groe...,Klikbaar: AH Nederlandse witte asperges 500 gr...,https://www.ah.nl/bonus/groep/794197?week=20,Albertijn,11 mei,17 mei
1,AH Broccoli,Klikbaar: AH Broccoli uitgelicht per 500 gram ...,https://www.ah.nl/bonus/groep/794193?week=20,Albertijn,11 mei,17 mei
2,AH Trostomaten,Klikbaar: AH Trostomaten uitgelicht per 500 gr...,https://www.ah.nl/bonus/groep/794194?week=20,Albertijn,11 mei,17 mei
3,Alle AH Kleinverpakkingen groentegemak,Klikbaar: Alle AH Kleinverpakkingen groentegem...,https://www.ah.nl/bonus/groep/784569?week=20,Albertijn,11 mei,17 mei
4,AH Snoepgroente tomaat 500 gram en komkommer 4...,Klikbaar: AH Snoepgroente tomaat 500 gram en k...,https://www.ah.nl/bonus/groep/794195?week=20,Albertijn,11 mei,17 mei
...,...,...,...,...,...,...
199,Gliss Serum daily oil,Klikbaar: Gliss Serum daily oil 67 ml 1+1 grat...,https://www.ah.nl/bonus/groep/-21602?week=20,Albertijn,11 mei,17 mei
200,Gillette Mach 3 scheersysteem turbo 2,Klikbaar: Gillette Mach 3 scheersysteem turbo ...,https://www.ah.nl/bonus/groep/-21601?week=20,Albertijn,11 mei,17 mei
201,Etos tandenborstel,Klikbaar: Etos tandenborstel 1 stuks 2e halve ...,https://www.ah.nl/bonus/groep/-21597?week=20,Albertijn,11 mei,17 mei
202,Etos gezichtsverzorging,Klikbaar: Etos gezichtsverzorging Bijv. Etos E...,https://www.ah.nl/bonus/groep/-21591?week=20,Albertijn,11 mei,17 mei
203,Drs Leenarts,Klikbaar: Drs Leenarts Bijv. Drs. Leenarts Dag...,https://www.ah.nl/bonus/groep/-21588?week=20,Albertijn,11 mei,17 mei

In [17]:
df["discount"] = df["discount"].str.split(":")
df

,product,discount,link,store,start_date,end_date
0,AH Nederlandse witte asperges 500 gram of groe...,"[Klikbaar, AH Nederlandse witte asperges 500 ...",https://www.ah.nl/bonus/groep/794197?week=20,Albertijn,11 mei,17 mei
1,AH Broccoli,"[Klikbaar, AH Broccoli uitgelicht per 500 gra...",https://www.ah.nl/bonus/groep/794193?week=20,Albertijn,11 mei,17 mei
2,AH Trostomaten,"[Klikbaar, AH Trostomaten uitgelicht per 500 ...",https://www.ah.nl/bonus/groep/794194?week=20,Albertijn,11 mei,17 mei
3,Alle AH Kleinverpakkingen groentegemak,"[Klikbaar, Alle AH Kleinverpakkingen groenteg...",https://www.ah.nl/bonus/groep/784569?week=20,Albertijn,11 mei,17 mei
4,AH Snoepgroente tomaat 500 gram en komkommer 4...,"[Klikbaar, AH Snoepgroente tomaat 500 gram en...",https://www.ah.nl/bonus/groep/794195?week=20,Albertijn,11 mei,17 mei
...,...,...,...,...,...,...
199,Gliss Serum daily oil,"[Klikbaar, Gliss Serum daily oil 67 ml 1+1 gr...",https://www.ah.nl/bonus/groep/-21602?week=20,Albertijn,11 mei,17 mei
200,Gillette Mach 3 scheersysteem turbo 2,"[Klikbaar, Gillette Mach 3 scheersysteem turb...",https://www.ah.nl/bonus/groep/-21601?week=20,Albertijn,11 mei,17 mei
201,Etos tandenborstel,"[Klikbaar, Etos tandenborstel 1 stuks 2e halv...",https://www.ah.nl/bonus/groep/-21597?week=20,Albertijn,11 mei,17 mei
202,Etos gezichtsverzorging,"[Klikbaar, Etos gezichtsverzorging Bijv. Etos...",https://www.ah.nl/bonus/groep/-21591?week=20,Albertijn,11 mei,17 mei
203,Drs Leenarts,"[Klikbaar, Drs Leenarts Bijv. Drs. Leenarts D...",https://www.ah.nl/bonus/groep/-21588?week=20,Albertijn,11 mei,17 mei

In [18]:
df["discount"] = df["discount"].str[1]
df

,product,discount,link,store,start_date,end_date
0,AH Nederlandse witte asperges 500 gram of groe...,AH Nederlandse witte asperges 500 gram of gro...,https://www.ah.nl/bonus/groep/794197?week=20,Albertijn,11 mei,17 mei
1,AH Broccoli,AH Broccoli uitgelicht per 500 gram 1.09 Alle...,https://www.ah.nl/bonus/groep/794193?week=20,Albertijn,11 mei,17 mei
2,AH Trostomaten,AH Trostomaten uitgelicht per 500 gram 0.49 A...,https://www.ah.nl/bonus/groep/794194?week=20,Albertijn,11 mei,17 mei
3,Alle AH Kleinverpakkingen groentegemak,Alle AH Kleinverpakkingen groentegemak 2 voor...,https://www.ah.nl/bonus/groep/784569?week=20,Albertijn,11 mei,17 mei
4,AH Snoepgroente tomaat 500 gram en komkommer 4...,AH Snoepgroente tomaat 500 gram en komkommer ...,https://www.ah.nl/bonus/groep/794195?week=20,Albertijn,11 mei,17 mei
...,...,...,...,...,...,...
199,Gliss Serum daily oil,Gliss Serum daily oil 67 ml 1+1 gratis van 23...,https://www.ah.nl/bonus/groep/-21602?week=20,Albertijn,11 mei,17 mei
200,Gillette Mach 3 scheersysteem turbo 2,Gillette Mach 3 scheersysteem turbo 2 1 stuks...,https://www.ah.nl/bonus/groep/-21601?week=20,Albertijn,11 mei,17 mei
201,Etos tandenborstel,Etos tandenborstel 1 stuks 2e halve prijs van...,https://www.ah.nl/bonus/groep/-21597?week=20,Albertijn,11 mei,17 mei
202,Etos gezichtsverzorging,Etos gezichtsverzorging Bijv. Etos Eye make-u...,https://www.ah.nl/bonus/groep/-21591?week=20,Albertijn,11 mei,17 mei
203,Drs Leenarts,Drs Leenarts Bijv. Drs. Leenarts Dagcreme SPF...,https://www.ah.nl/bonus/groep/-21588?week=20,Albertijn,11 mei,17 mei

In [19]:
#Deleting all rows which have bezorging.
df = df[~df["product"].str.contains("bezorging", case=False, na=False)]
df

,product,discount,link,store,start_date,end_date
0,AH Nederlandse witte asperges 500 gram of groe...,AH Nederlandse witte asperges 500 gram of gro...,https://www.ah.nl/bonus/groep/794197?week=20,Albertijn,11 mei,17 mei
1,AH Broccoli,AH Broccoli uitgelicht per 500 gram 1.09 Alle...,https://www.ah.nl/bonus/groep/794193?week=20,Albertijn,11 mei,17 mei
2,AH Trostomaten,AH Trostomaten uitgelicht per 500 gram 0.49 A...,https://www.ah.nl/bonus/groep/794194?week=20,Albertijn,11 mei,17 mei
3,Alle AH Kleinverpakkingen groentegemak,Alle AH Kleinverpakkingen groentegemak 2 voor...,https://www.ah.nl/bonus/groep/784569?week=20,Albertijn,11 mei,17 mei
4,AH Snoepgroente tomaat 500 gram en komkommer 4...,AH Snoepgroente tomaat 500 gram en komkommer ...,https://www.ah.nl/bonus/groep/794195?week=20,Albertijn,11 mei,17 mei
...,...,...,...,...,...,...
199,Gliss Serum daily oil,Gliss Serum daily oil 67 ml 1+1 gratis van 23...,https://www.ah.nl/bonus/groep/-21602?week=20,Albertijn,11 mei,17 mei
200,Gillette Mach 3 scheersysteem turbo 2,Gillette Mach 3 scheersysteem turbo 2 1 stuks...,https://www.ah.nl/bonus/groep/-21601?week=20,Albertijn,11 mei,17 mei
201,Etos tandenborstel,Etos tandenborstel 1 stuks 2e halve prijs van...,https://www.ah.nl/bonus/groep/-21597?week=20,Albertijn,11 mei,17 mei
202,Etos gezichtsverzorging,Etos gezichtsverzorging Bijv. Etos Eye make-u...,https://www.ah.nl/bonus/groep/-21591?week=20,Albertijn,11 mei,17 mei
203,Drs Leenarts,Drs Leenarts Bijv. Drs. Leenarts Dagcreme SPF...,https://www.ah.nl/bonus/groep/-21588?week=20,Albertijn,11 mei,17 mei

In [20]:
df = df[~df["product"].str.contains("Online", case=True, na=False)]
df

,product,discount,link,store,start_date,end_date
0,AH Nederlandse witte asperges 500 gram of groe...,AH Nederlandse witte asperges 500 gram of gro...,https://www.ah.nl/bonus/groep/794197?week=20,Albertijn,11 mei,17 mei
1,AH Broccoli,AH Broccoli uitgelicht per 500 gram 1.09 Alle...,https://www.ah.nl/bonus/groep/794193?week=20,Albertijn,11 mei,17 mei
2,AH Trostomaten,AH Trostomaten uitgelicht per 500 gram 0.49 A...,https://www.ah.nl/bonus/groep/794194?week=20,Albertijn,11 mei,17 mei
3,Alle AH Kleinverpakkingen groentegemak,Alle AH Kleinverpakkingen groentegemak 2 voor...,https://www.ah.nl/bonus/groep/784569?week=20,Albertijn,11 mei,17 mei
4,AH Snoepgroente tomaat 500 gram en komkommer 4...,AH Snoepgroente tomaat 500 gram en komkommer ...,https://www.ah.nl/bonus/groep/794195?week=20,Albertijn,11 mei,17 mei
...,...,...,...,...,...,...
199,Gliss Serum daily oil,Gliss Serum daily oil 67 ml 1+1 gratis van 23...,https://www.ah.nl/bonus/groep/-21602?week=20,Albertijn,11 mei,17 mei
200,Gillette Mach 3 scheersysteem turbo 2,Gillette Mach 3 scheersysteem turbo 2 1 stuks...,https://www.ah.nl/bonus/groep/-21601?week=20,Albertijn,11 mei,17 mei
201,Etos tandenborstel,Etos tandenborstel 1 stuks 2e halve prijs van...,https://www.ah.nl/bonus/groep/-21597?week=20,Albertijn,11 mei,17 mei
202,Etos gezichtsverzorging,Etos gezichtsverzorging Bijv. Etos Eye make-u...,https://www.ah.nl/bonus/groep/-21591?week=20,Albertijn,11 mei,17 mei
203,Drs Leenarts,Drs Leenarts Bijv. Drs. Leenarts Dagcreme SPF...,https://www.ah.nl/bonus/groep/-21588?week=20,Albertijn,11 mei,17 mei

In [21]:
#Removing all products which are online
target_index = df[df["product"].str.contains("OP=OP", case=True, na=False)].index[0]
df = df.loc[:target_index - 1]
df

,product,discount,link,store,start_date,end_date
0,AH Nederlandse witte asperges 500 gram of groe...,AH Nederlandse witte asperges 500 gram of gro...,https://www.ah.nl/bonus/groep/794197?week=20,Albertijn,11 mei,17 mei
1,AH Broccoli,AH Broccoli uitgelicht per 500 gram 1.09 Alle...,https://www.ah.nl/bonus/groep/794193?week=20,Albertijn,11 mei,17 mei
2,AH Trostomaten,AH Trostomaten uitgelicht per 500 gram 0.49 A...,https://www.ah.nl/bonus/groep/794194?week=20,Albertijn,11 mei,17 mei
3,Alle AH Kleinverpakkingen groentegemak,Alle AH Kleinverpakkingen groentegemak 2 voor...,https://www.ah.nl/bonus/groep/784569?week=20,Albertijn,11 mei,17 mei
4,AH Snoepgroente tomaat 500 gram en komkommer 4...,AH Snoepgroente tomaat 500 gram en komkommer ...,https://www.ah.nl/bonus/groep/794195?week=20,Albertijn,11 mei,17 mei
...,...,...,...,...,...,...
158,AH BBQ accessoires,AH BBQ accessoires Bonus,https://www.ah.nl/bonus/groep/779107?week=20,Albertijn,11 mei,17 mei
159,Weber BBQ accessoires,Weber BBQ accessoires Bonus,https://www.ah.nl/bonus/groep/779600?week=20,Albertijn,11 mei,17 mei
160,Grill Guru Houtskool 10 kilo,Grill Guru Houtskool 10 kilo voor 18.95,https://www.ah.nl/bonus/groep/779602?week=20,Albertijn,11 mei,17 mei
161,Grill Guru BBQ accessoires,Grill Guru BBQ accessoires 25% korting,https://www.ah.nl/bonus/groep/779606?week=20,Albertijn,11 mei,17 mei
162,AH Muffin rozijn amandel hazelnoot,AH Muffin rozijn amandel hazelnoot online Bonus,https://www.ah.nl/bonus/groep/-21768?week=20,Albertijn,11 mei,17 mei

In [22]:
def discount_name_cleaner(row):
    discount = str(row["discount"])
    product = str(row["product"])
    if(product in discount):
        return discount.replace(product, "").strip()
    return discount

df_new = df.copy()
df_new["discount"] = df_new.apply(discount_name_cleaner, axis=1)
df_new

,product,discount,link,store,start_date,end_date
0,AH Nederlandse witte asperges 500 gram of groe...,2 stuks 50% 1 stuk 30%,https://www.ah.nl/bonus/groep/794197?week=20,Albertijn,11 mei,17 mei
1,AH Broccoli,uitgelicht per 500 gram 1.09 Alleen in de winkel,https://www.ah.nl/bonus/groep/794193?week=20,Albertijn,11 mei,17 mei
2,AH Trostomaten,uitgelicht per 500 gram 0.49 Alleen in de winkel,https://www.ah.nl/bonus/groep/794194?week=20,Albertijn,11 mei,17 mei
3,Alle AH Kleinverpakkingen groentegemak,2 voor 2.49,https://www.ah.nl/bonus/groep/784569?week=20,Albertijn,11 mei,17 mei
4,AH Snoepgroente tomaat 500 gram en komkommer 4...,2 voor 4.49,https://www.ah.nl/bonus/groep/794195?week=20,Albertijn,11 mei,17 mei
...,...,...,...,...,...,...
158,AH BBQ accessoires,Bonus,https://www.ah.nl/bonus/groep/779107?week=20,Albertijn,11 mei,17 mei
159,Weber BBQ accessoires,Bonus,https://www.ah.nl/bonus/groep/779600?week=20,Albertijn,11 mei,17 mei
160,Grill Guru Houtskool 10 kilo,voor 18.95,https://www.ah.nl/bonus/groep/779602?week=20,Albertijn,11 mei,17 mei
161,Grill Guru BBQ accessoires,25% korting,https://www.ah.nl/bonus/groep/779606?week=20,Albertijn,11 mei,17 mei
162,AH Muffin rozijn amandel hazelnoot,online Bonus,https://www.ah.nl/bonus/groep/-21768?week=20,Albertijn,11 mei,17 mei

In [23]:
#removing Allen in winkel
def winkel(text):
    wink = "Alleen in de winkel"
    if wink in text:
        return text.replace(wink, "").strip()
    return text
df_new["discount"] = df_new["discount"].apply(winkel)
df_new

,product,discount,link,store,start_date,end_date
0,AH Nederlandse witte asperges 500 gram of groe...,2 stuks 50% 1 stuk 30%,https://www.ah.nl/bonus/groep/794197?week=20,Albertijn,11 mei,17 mei
1,AH Broccoli,uitgelicht per 500 gram 1.09,https://www.ah.nl/bonus/groep/794193?week=20,Albertijn,11 mei,17 mei
2,AH Trostomaten,uitgelicht per 500 gram 0.49,https://www.ah.nl/bonus/groep/794194?week=20,Albertijn,11 mei,17 mei
3,Alle AH Kleinverpakkingen groentegemak,2 voor 2.49,https://www.ah.nl/bonus/groep/784569?week=20,Albertijn,11 mei,17 mei
4,AH Snoepgroente tomaat 500 gram en komkommer 4...,2 voor 4.49,https://www.ah.nl/bonus/groep/794195?week=20,Albertijn,11 mei,17 mei
...,...,...,...,...,...,...
158,AH BBQ accessoires,Bonus,https://www.ah.nl/bonus/groep/779107?week=20,Albertijn,11 mei,17 mei
159,Weber BBQ accessoires,Bonus,https://www.ah.nl/bonus/groep/779600?week=20,Albertijn,11 mei,17 mei
160,Grill Guru Houtskool 10 kilo,voor 18.95,https://www.ah.nl/bonus/groep/779602?week=20,Albertijn,11 mei,17 mei
161,Grill Guru BBQ accessoires,25% korting,https://www.ah.nl/bonus/groep/779606?week=20,Albertijn,11 mei,17 mei
162,AH Muffin rozijn amandel hazelnoot,online Bonus,https://www.ah.nl/bonus/groep/-21768?week=20,Albertijn,11 mei,17 mei

In [26]:
df_new.to_json('../../data/AH_cleaned_4.json', orient='records', indent=4, force_ascii=False)