In [89]:
import pandas as pd
import re

In [90]:
df = pd.read_json("../scraping/j_raw_deals_2.json")

In [91]:
df

,product,discount,link,store,date
0,Frambozen of Hollandse aardbeien [Kompas JumRo...,"2 voor 6,00",https://www.jumbo.com/aanbiedingen/frambozen-o...,Jumbo,wo 6 t/m di 12 mei
1,Combikorting fruit [Kompas JumRouterLink],"Combikorting 2 voor 4,50",https://www.jumbo.com/aanbiedingen/combikortin...,Jumbo,wo 6 t/m di 12 mei
2,Jumbo roerbakmixen [Kompas JumRouterLink],"2 voor 3,50",https://www.jumbo.com/aanbiedingen/jumbo-roerb...,Jumbo,wo 6 t/m di 12 mei
3,Alle Pink Lady [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/alle-pink-l...,Jumbo,wo 6 t/m di 12 mei
4,Jumbo fijnproevers asperges geschild of witte ...,"voor 4,99",https://www.jumbo.com/aanbiedingen/jumbo-fijnp...,Jumbo,wo 6 t/m di 12 mei
...,...,...,...,...,...
92,Alle Pink Lady [Kompas JumRouterLink],"Alleen in de winkel 2,49 per kilo",https://www.jumbo.com/aanbiedingen/alle-pink-l...,Jumbo,wo 6 t/m di 12 mei
93,Baileys [Kompas JumRouterLink],"Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/baileys/301...,Jumbo,wo 6 t/m di 12 mei
94,"Licor Beirao, Southern Comfort, Grand Marnier ...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/licor-beira...,Jumbo,wo 6 t/m di 12 mei
95,Bacardi [Kompas JumRouterLink],"Alleen in de slijterij voor 14,99",https://www.jumbo.com/aanbiedingen/bacardi/301...,Jumbo,wo 6 t/m di 12 mei
96,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,wo 4 feb t/m wo 30 dec

In [92]:
def wo_remove(text):
    remove = "wo"
    remove_2 = "di"
    text = text.replace(remove, "")
    text = text.replace(remove_2, "").strip()
    return text

df["date"] = df["date"].apply(wo_remove)
df

,product,discount,link,store,date
0,Frambozen of Hollandse aardbeien [Kompas JumRo...,"2 voor 6,00",https://www.jumbo.com/aanbiedingen/frambozen-o...,Jumbo,6 t/m 12 mei
1,Combikorting fruit [Kompas JumRouterLink],"Combikorting 2 voor 4,50",https://www.jumbo.com/aanbiedingen/combikortin...,Jumbo,6 t/m 12 mei
2,Jumbo roerbakmixen [Kompas JumRouterLink],"2 voor 3,50",https://www.jumbo.com/aanbiedingen/jumbo-roerb...,Jumbo,6 t/m 12 mei
3,Alle Pink Lady [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/alle-pink-l...,Jumbo,6 t/m 12 mei
4,Jumbo fijnproevers asperges geschild of witte ...,"voor 4,99",https://www.jumbo.com/aanbiedingen/jumbo-fijnp...,Jumbo,6 t/m 12 mei
...,...,...,...,...,...
92,Alle Pink Lady [Kompas JumRouterLink],"Alleen in de winkel 2,49 per kilo",https://www.jumbo.com/aanbiedingen/alle-pink-l...,Jumbo,6 t/m 12 mei
93,Baileys [Kompas JumRouterLink],"Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/baileys/301...,Jumbo,6 t/m 12 mei
94,"Licor Beirao, Southern Comfort, Grand Marnier ...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/licor-beira...,Jumbo,6 t/m 12 mei
95,Bacardi [Kompas JumRouterLink],"Alleen in de slijterij voor 14,99",https://www.jumbo.com/aanbiedingen/bacardi/301...,Jumbo,6 t/m 12 mei
96,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,4 feb t/m 30 dec

In [93]:
df["date"] = df["date"].str.split("t/m")

def split_date(date_val):

    if isinstance(date_val, list):
        cleaned = ' '.join(str(x) for x in date_val)
    else:
        cleaned = str(date_val)

    cleaned = cleaned.replace('\xa0', ' ').replace('NBSP', '').strip()
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()

    same_month = re.match(r'(\d+)\s+(\d+)\s+(\w+)', cleaned)
    if same_month:
        day1, day2, month = same_month.groups()
        return f"{day1} {month}", f"{day2} {month}"

    diff_month = re.match(r'(\d+)\s+(\w+)\s+(\d+)\s+(\w+)', cleaned)
    if diff_month:
        day1, month1, day2, month2 = diff_month.groups()
        return f"{day1} {month1}", f"{day2} {month2}"

    return cleaned, cleaned

df[['start_date', 'end_date']] = df['date'].apply(
    lambda x: pd.Series(split_date(x))
)

             date start_date end_date
0  [6 ,   12 mei]      6 mei   12 mei
1  [6 ,   12 mei]      6 mei   12 mei
2  [6 ,   12 mei]      6 mei   12 mei
3  [6 ,   12 mei]      6 mei   12 mei
4  [6 ,   12 mei]      6 mei   12 mei
5  [6 ,   12 mei]      6 mei   12 mei
6  [6 ,   12 mei]      6 mei   12 mei
7  [6 ,   12 mei]      6 mei   12 mei
8  [6 ,   19 mei]      6 mei   19 mei
9  [6 ,   12 mei]      6 mei   12 mei

In [94]:
df = df.drop("date", axis=1)
df

,product,discount,link,store,start_date,end_date
0,Frambozen of Hollandse aardbeien [Kompas JumRo...,"2 voor 6,00",https://www.jumbo.com/aanbiedingen/frambozen-o...,Jumbo,6 mei,12 mei
1,Combikorting fruit [Kompas JumRouterLink],"Combikorting 2 voor 4,50",https://www.jumbo.com/aanbiedingen/combikortin...,Jumbo,6 mei,12 mei
2,Jumbo roerbakmixen [Kompas JumRouterLink],"2 voor 3,50",https://www.jumbo.com/aanbiedingen/jumbo-roerb...,Jumbo,6 mei,12 mei
3,Alle Pink Lady [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/alle-pink-l...,Jumbo,6 mei,12 mei
4,Jumbo fijnproevers asperges geschild of witte ...,"voor 4,99",https://www.jumbo.com/aanbiedingen/jumbo-fijnp...,Jumbo,6 mei,12 mei
...,...,...,...,...,...,...
92,Alle Pink Lady [Kompas JumRouterLink],"Alleen in de winkel 2,49 per kilo",https://www.jumbo.com/aanbiedingen/alle-pink-l...,Jumbo,6 mei,12 mei
93,Baileys [Kompas JumRouterLink],"Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/baileys/301...,Jumbo,6 mei,12 mei
94,"Licor Beirao, Southern Comfort, Grand Marnier ...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/licor-beira...,Jumbo,6 mei,12 mei
95,Bacardi [Kompas JumRouterLink],"Alleen in de slijterij voor 14,99",https://www.jumbo.com/aanbiedingen/bacardi/301...,Jumbo,6 mei,12 mei
96,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,4 feb,30 dec

In [95]:
def product_clean(text):
    word = "[Kompas JumRouterLink]"
    text = text.replace(word, "").strip()
    return text

df["product"] = df["product"].apply(product_clean)
df

,product,discount,link,store,start_date,end_date
0,Frambozen of Hollandse aardbeien,"2 voor 6,00",https://www.jumbo.com/aanbiedingen/frambozen-o...,Jumbo,6 mei,12 mei
1,Combikorting fruit,"Combikorting 2 voor 4,50",https://www.jumbo.com/aanbiedingen/combikortin...,Jumbo,6 mei,12 mei
2,Jumbo roerbakmixen,"2 voor 3,50",https://www.jumbo.com/aanbiedingen/jumbo-roerb...,Jumbo,6 mei,12 mei
3,Alle Pink Lady,"voor 2,49",https://www.jumbo.com/aanbiedingen/alle-pink-l...,Jumbo,6 mei,12 mei
4,Jumbo fijnproevers asperges geschild of witte ...,"voor 4,99",https://www.jumbo.com/aanbiedingen/jumbo-fijnp...,Jumbo,6 mei,12 mei
...,...,...,...,...,...,...
92,Alle Pink Lady,"Alleen in de winkel 2,49 per kilo",https://www.jumbo.com/aanbiedingen/alle-pink-l...,Jumbo,6 mei,12 mei
93,Baileys,"Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/baileys/301...,Jumbo,6 mei,12 mei
94,"Licor Beirao, Southern Comfort, Grand Marnier ...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/licor-beira...,Jumbo,6 mei,12 mei
95,Bacardi,"Alleen in de slijterij voor 14,99",https://www.jumbo.com/aanbiedingen/bacardi/301...,Jumbo,6 mei,12 mei
96,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,4 feb,30 dec

In [96]:
#removing products which are online or liquor store
df = df[~df["discount"].str.contains("Alleen online", case=True, na=False)]
df = df[~df["discount"].str.contains("slijterij", case=True, na=False)]
df = df[df['product'] != 'Welke biermerken zijn bij jouw Jumbo in de aanbieding?']

In [97]:
df

,product,discount,link,store,start_date,end_date
0,Frambozen of Hollandse aardbeien,"2 voor 6,00",https://www.jumbo.com/aanbiedingen/frambozen-o...,Jumbo,6 mei,12 mei
1,Combikorting fruit,"Combikorting 2 voor 4,50",https://www.jumbo.com/aanbiedingen/combikortin...,Jumbo,6 mei,12 mei
2,Jumbo roerbakmixen,"2 voor 3,50",https://www.jumbo.com/aanbiedingen/jumbo-roerb...,Jumbo,6 mei,12 mei
3,Alle Pink Lady,"voor 2,49",https://www.jumbo.com/aanbiedingen/alle-pink-l...,Jumbo,6 mei,12 mei
4,Jumbo fijnproevers asperges geschild of witte ...,"voor 4,99",https://www.jumbo.com/aanbiedingen/jumbo-fijnp...,Jumbo,6 mei,12 mei
...,...,...,...,...,...,...
87,Alle Marcel's Green Soap,1+1 gratis,https://www.jumbo.com/aanbiedingen/alle-marcel...,Jumbo,6 mei,19 mei
88,Alle Robijn wasverzachters of wasparfums,1+1 gratis,https://www.jumbo.com/aanbiedingen/alle-robijn...,Jumbo,6 mei,19 mei
89,Alle Witte Reus of Fleuril wasmiddel,2+3 gratis,https://www.jumbo.com/aanbiedingen/alle-witte-...,Jumbo,6 mei,12 mei
91,Zespri Sungold kiwi,"Alleen in de winkel 2,79 per 500 gram",https://www.jumbo.com/aanbiedingen/zespri-sung...,Jumbo,6 mei,12 mei
92,Alle Pink Lady,"Alleen in de winkel 2,49 per kilo",https://www.jumbo.com/aanbiedingen/alle-pink-l...,Jumbo,6 mei,12 mei

In [98]:
df.to_json('data/J_cleaned_2.json', orient='records', indent=4, force_ascii=False)