In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_json("../scraping/j_raw_deals_2.json", convert_dates=False)

In [3]:
df

,product,discount,link,store,date,image_url
0,Gesneden fruit [Kompas JumRouterLink],"2 voor 3,99",https://www.jumbo.com/aanbiedingen/gesneden-fr...,Jumbo,wo 24 t/m di 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
1,Zespri kiwi Sungold [Kompas JumRouterLink],"voor 4,99",https://www.jumbo.com/aanbiedingen/zespri-kiwi...,Jumbo,wo 24 t/m di 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
2,Nederlandse aardbeien [Kompas JumRouterLink],"voor 2,99",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,wo 24 t/m di 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
3,Avocado [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/avocado/301...,Jumbo,wo 24 t/m di 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
4,Bimi [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/bimi/3019129,Jumbo,wo 24 t/m di 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
...,...,...,...,...,...,...
122,Broccoli [Kompas JumRouterLink],"Alleen in de winkel 1,19 per 500 gram",https://www.jumbo.com/aanbiedingen/broccoli/30...,Jumbo,wo 24 t/m di 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
123,"Captain Morgan rum, Smirnoff vodka, Gordon's g...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/captain-mor...,Jumbo,wo 24 t/m di 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
124,Johnnie Walker whisky [Kompas JumRouterLink],"Alleen in de slijterij 5,00 korting",https://www.jumbo.com/aanbiedingen/johnnie-wal...,Jumbo,wo 24 t/m di 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
125,Bacardi [Kompas JumRouterLink],"Alleen in de slijterij voor 14,99",https://www.jumbo.com/aanbiedingen/bacardi/301...,Jumbo,wo 24 t/m di 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
126,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,wo 4 feb t/m wo 30 dec,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...

In [4]:
def wo_remove(text):
    remove = "wo"
    remove_2 = "di"
    text = text.replace(remove, "")
    text = text.replace(remove_2, "").strip()
    return text

df["date"] = df["date"].apply(wo_remove)
df

,product,discount,link,store,date,image_url
0,Gesneden fruit [Kompas JumRouterLink],"2 voor 3,99",https://www.jumbo.com/aanbiedingen/gesneden-fr...,Jumbo,24 t/m 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
1,Zespri kiwi Sungold [Kompas JumRouterLink],"voor 4,99",https://www.jumbo.com/aanbiedingen/zespri-kiwi...,Jumbo,24 t/m 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
2,Nederlandse aardbeien [Kompas JumRouterLink],"voor 2,99",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,24 t/m 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
3,Avocado [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/avocado/301...,Jumbo,24 t/m 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
4,Bimi [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/bimi/3019129,Jumbo,24 t/m 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
...,...,...,...,...,...,...
122,Broccoli [Kompas JumRouterLink],"Alleen in de winkel 1,19 per 500 gram",https://www.jumbo.com/aanbiedingen/broccoli/30...,Jumbo,24 t/m 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
123,"Captain Morgan rum, Smirnoff vodka, Gordon's g...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/captain-mor...,Jumbo,24 t/m 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
124,Johnnie Walker whisky [Kompas JumRouterLink],"Alleen in de slijterij 5,00 korting",https://www.jumbo.com/aanbiedingen/johnnie-wal...,Jumbo,24 t/m 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
125,Bacardi [Kompas JumRouterLink],"Alleen in de slijterij voor 14,99",https://www.jumbo.com/aanbiedingen/bacardi/301...,Jumbo,24 t/m 30 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
126,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,4 feb t/m 30 dec,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...

In [5]:
df["date"] = df["date"].str.split("t/m")

def split_date(date_val):

    if isinstance(date_val, list):
        cleaned = ' '.join(str(x) for x in date_val)
    else:
        cleaned = str(date_val)

    cleaned = cleaned.replace('\xa0', ' ').replace('NBSP', '').strip()
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()

    same_month = re.match(r'(\d+)\s+(\d+)\s+(\w+)', cleaned)
    if same_month:
        day1, day2, month = same_month.groups()
        return f"{day1} {month}", f"{day2} {month}"

    diff_month = re.match(r'(\d+)\s+(\w+)\s+(\d+)\s+(\w+)', cleaned)
    if diff_month:
        day1, month1, day2, month2 = diff_month.groups()
        return f"{day1} {month1}", f"{day2} {month2}"

    return cleaned, cleaned

df[['start_date', 'end_date']] = df['date'].apply(
    lambda x: pd.Series(split_date(x))
)

In [6]:
df

,product,discount,link,store,date,image_url,start_date,end_date
0,Gesneden fruit [Kompas JumRouterLink],"2 voor 3,99",https://www.jumbo.com/aanbiedingen/gesneden-fr...,Jumbo,"[24 , 30 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
1,Zespri kiwi Sungold [Kompas JumRouterLink],"voor 4,99",https://www.jumbo.com/aanbiedingen/zespri-kiwi...,Jumbo,"[24 , 30 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
2,Nederlandse aardbeien [Kompas JumRouterLink],"voor 2,99",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,"[24 , 30 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
3,Avocado [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/avocado/301...,Jumbo,"[24 , 30 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
4,Bimi [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/bimi/3019129,Jumbo,"[24 , 30 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
...,...,...,...,...,...,...,...,...
122,Broccoli [Kompas JumRouterLink],"Alleen in de winkel 1,19 per 500 gram",https://www.jumbo.com/aanbiedingen/broccoli/30...,Jumbo,"[24 , 30 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
123,"Captain Morgan rum, Smirnoff vodka, Gordon's g...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/captain-mor...,Jumbo,"[24 , 30 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
124,Johnnie Walker whisky [Kompas JumRouterLink],"Alleen in de slijterij 5,00 korting",https://www.jumbo.com/aanbiedingen/johnnie-wal...,Jumbo,"[24 , 30 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
125,Bacardi [Kompas JumRouterLink],"Alleen in de slijterij voor 14,99",https://www.jumbo.com/aanbiedingen/bacardi/301...,Jumbo,"[24 , 30 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
126,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,"[4 feb , 30 dec]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,4 feb,30 dec

In [7]:
df = df.drop("date", axis=1)
df

,product,discount,link,store,image_url,start_date,end_date
0,Gesneden fruit [Kompas JumRouterLink],"2 voor 3,99",https://www.jumbo.com/aanbiedingen/gesneden-fr...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
1,Zespri kiwi Sungold [Kompas JumRouterLink],"voor 4,99",https://www.jumbo.com/aanbiedingen/zespri-kiwi...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
2,Nederlandse aardbeien [Kompas JumRouterLink],"voor 2,99",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
3,Avocado [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/avocado/301...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
4,Bimi [Kompas JumRouterLink],"voor 2,49",https://www.jumbo.com/aanbiedingen/bimi/3019129,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
...,...,...,...,...,...,...,...
122,Broccoli [Kompas JumRouterLink],"Alleen in de winkel 1,19 per 500 gram",https://www.jumbo.com/aanbiedingen/broccoli/30...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
123,"Captain Morgan rum, Smirnoff vodka, Gordon's g...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/captain-mor...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
124,Johnnie Walker whisky [Kompas JumRouterLink],"Alleen in de slijterij 5,00 korting",https://www.jumbo.com/aanbiedingen/johnnie-wal...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
125,Bacardi [Kompas JumRouterLink],"Alleen in de slijterij voor 14,99",https://www.jumbo.com/aanbiedingen/bacardi/301...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
126,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,4 feb,30 dec

In [8]:
def product_clean(text):
    word = "[Kompas JumRouterLink]"
    text = text.replace(word, "").strip()
    return text

df["product"] = df["product"].apply(product_clean)
df

,product,discount,link,store,image_url,start_date,end_date
0,Gesneden fruit,"2 voor 3,99",https://www.jumbo.com/aanbiedingen/gesneden-fr...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
1,Zespri kiwi Sungold,"voor 4,99",https://www.jumbo.com/aanbiedingen/zespri-kiwi...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
2,Nederlandse aardbeien,"voor 2,99",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
3,Avocado,"voor 2,49",https://www.jumbo.com/aanbiedingen/avocado/301...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
4,Bimi,"voor 2,49",https://www.jumbo.com/aanbiedingen/bimi/3019129,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
...,...,...,...,...,...,...,...
122,Broccoli,"Alleen in de winkel 1,19 per 500 gram",https://www.jumbo.com/aanbiedingen/broccoli/30...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
123,"Captain Morgan rum, Smirnoff vodka, Gordon's g...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/captain-mor...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
124,Johnnie Walker whisky,"Alleen in de slijterij 5,00 korting",https://www.jumbo.com/aanbiedingen/johnnie-wal...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
125,Bacardi,"Alleen in de slijterij voor 14,99",https://www.jumbo.com/aanbiedingen/bacardi/301...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
126,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,4 feb,30 dec

In [9]:
#removing products which are online or liquor store
df = df[~df["discount"].str.contains("Alleen online", case=True, na=False)]
df = df[~df["discount"].str.contains("slijterij", case=True, na=False)]
df = df[df['product'] != 'Welke biermerken zijn bij jouw Jumbo in de aanbieding?']

In [10]:
df

,product,discount,link,store,image_url,start_date,end_date
0,Gesneden fruit,"2 voor 3,99",https://www.jumbo.com/aanbiedingen/gesneden-fr...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
1,Zespri kiwi Sungold,"voor 4,99",https://www.jumbo.com/aanbiedingen/zespri-kiwi...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
2,Nederlandse aardbeien,"voor 2,99",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
3,Avocado,"voor 2,49",https://www.jumbo.com/aanbiedingen/avocado/301...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
4,Bimi,"voor 2,49",https://www.jumbo.com/aanbiedingen/bimi/3019129,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
...,...,...,...,...,...,...,...
117,Alle Finish of Vanish,1+1 gratis,https://www.jumbo.com/aanbiedingen/alle-finish...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
118,"Marcel's Green Soap, Cillit Bang of Destop was...",1+1 gratis,https://www.jumbo.com/aanbiedingen/marcels-gre...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
119,Alle Airwick,1+1 gratis,https://www.jumbo.com/aanbiedingen/alle-airwic...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
121,Conference peren,"Alleen in de winkel 1,59 per kilo",https://www.jumbo.com/aanbiedingen/conference-...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
122,Broccoli,"Alleen in de winkel 1,19 per 500 gram",https://www.jumbo.com/aanbiedingen/broccoli/30...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun

In [11]:
def winkel(text):
    wink = "Alleen in de winkel"
    if wink in text:
        return text.replace(wink, "").strip()
    return text

df["discount"] = df["discount"].apply(winkel)
df

,product,discount,link,store,image_url,start_date,end_date
0,Gesneden fruit,"2 voor 3,99",https://www.jumbo.com/aanbiedingen/gesneden-fr...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
1,Zespri kiwi Sungold,"voor 4,99",https://www.jumbo.com/aanbiedingen/zespri-kiwi...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
2,Nederlandse aardbeien,"voor 2,99",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
3,Avocado,"voor 2,49",https://www.jumbo.com/aanbiedingen/avocado/301...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
4,Bimi,"voor 2,49",https://www.jumbo.com/aanbiedingen/bimi/3019129,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
...,...,...,...,...,...,...,...
117,Alle Finish of Vanish,1+1 gratis,https://www.jumbo.com/aanbiedingen/alle-finish...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
118,"Marcel's Green Soap, Cillit Bang of Destop was...",1+1 gratis,https://www.jumbo.com/aanbiedingen/marcels-gre...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
119,Alle Airwick,1+1 gratis,https://www.jumbo.com/aanbiedingen/alle-airwic...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
121,Conference peren,"1,59 per kilo",https://www.jumbo.com/aanbiedingen/conference-...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
122,Broccoli,"1,19 per 500 gram",https://www.jumbo.com/aanbiedingen/broccoli/30...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun

In [14]:
def discount_filter(df):
    remover = 'Gratis emblemen'
    rows_to_drop = []

    for idx in df.index:
        cell_value = str(df.loc[idx, 'discount'])
        if remover.lower() in cell_value.lower():
            rows_to_drop.append(idx)

    return df.drop(index=rows_to_drop)

new_df = discount_filter(df)
new_df

,product,discount,link,store,image_url,start_date,end_date
0,Gesneden fruit,"2 voor 3,99",https://www.jumbo.com/aanbiedingen/gesneden-fr...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
1,Zespri kiwi Sungold,"voor 4,99",https://www.jumbo.com/aanbiedingen/zespri-kiwi...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
2,Nederlandse aardbeien,"voor 2,99",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
3,Avocado,"voor 2,49",https://www.jumbo.com/aanbiedingen/avocado/301...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
4,Bimi,"voor 2,49",https://www.jumbo.com/aanbiedingen/bimi/3019129,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
...,...,...,...,...,...,...,...
117,Alle Finish of Vanish,1+1 gratis,https://www.jumbo.com/aanbiedingen/alle-finish...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
118,"Marcel's Green Soap, Cillit Bang of Destop was...",1+1 gratis,https://www.jumbo.com/aanbiedingen/marcels-gre...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
119,Alle Airwick,1+1 gratis,https://www.jumbo.com/aanbiedingen/alle-airwic...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
121,Conference peren,"1,59 per kilo",https://www.jumbo.com/aanbiedingen/conference-...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun
122,Broccoli,"1,19 per 500 gram",https://www.jumbo.com/aanbiedingen/broccoli/30...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,24 jun,30 jun

In [15]:
new_df.to_json('../../data/J_cleaned_8.json', orient='records', indent=4, force_ascii=False)