In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_json("../scraping/j_raw_deals_2.json", convert_dates=False)

In [3]:
df

,product,discount,link,store,date,image_url
0,Jumbo verse friet [Kompas JumRouterLink],"voor 1,99",https://www.jumbo.com/aanbiedingen/jumbo-verse...,Jumbo,wo 17 t/m di 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
1,Jumbo rauwkost [Kompas JumRouterLink],"voor 1,49",https://www.jumbo.com/aanbiedingen/jumbo-rauwk...,Jumbo,wo 17 t/m di 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
2,"Rucola, Veldsla of melanges [Kompas JumRouterL...","voor 1,00",https://www.jumbo.com/aanbiedingen/rucola-veld...,Jumbo,wo 17 t/m di 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
3,Nederlandse aardbeien [Kompas JumRouterLink],"voor 2,39",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,wo 17 t/m di 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
4,Zoete punt paprika mix [Kompas JumRouterLink],"voor 1,79",https://www.jumbo.com/aanbiedingen/zoete-punt-...,Jumbo,wo 17 t/m di 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
...,...,...,...,...,...,...
104,Disaronno [Kompas JumRouterLink],"Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/disaronno/3...,Jumbo,wo 17 t/m di 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
105,Jack Daniels [Kompas JumRouterLink],"Alleen in de slijterij 5,00 korting",https://www.jumbo.com/aanbiedingen/jack-daniel...,Jumbo,wo 17 t/m di 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
106,"Malibu likeur, Absolut vodka of Havana rum [Ko...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/malibu-like...,Jumbo,wo 17 t/m di 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
107,Malt Whiskies [Kompas JumRouterLink],"Alleen in de slijterij 6,00 korting",https://www.jumbo.com/aanbiedingen/malt-whiski...,Jumbo,wo 17 t/m di 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
108,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,wo 4 feb t/m wo 30 dec,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...

In [4]:
def wo_remove(text):
    remove = "wo"
    remove_2 = "di"
    text = text.replace(remove, "")
    text = text.replace(remove_2, "").strip()
    return text

df["date"] = df["date"].apply(wo_remove)
df

,product,discount,link,store,date,image_url
0,Jumbo verse friet [Kompas JumRouterLink],"voor 1,99",https://www.jumbo.com/aanbiedingen/jumbo-verse...,Jumbo,17 t/m 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
1,Jumbo rauwkost [Kompas JumRouterLink],"voor 1,49",https://www.jumbo.com/aanbiedingen/jumbo-rauwk...,Jumbo,17 t/m 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
2,"Rucola, Veldsla of melanges [Kompas JumRouterL...","voor 1,00",https://www.jumbo.com/aanbiedingen/rucola-veld...,Jumbo,17 t/m 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
3,Nederlandse aardbeien [Kompas JumRouterLink],"voor 2,39",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,17 t/m 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
4,Zoete punt paprika mix [Kompas JumRouterLink],"voor 1,79",https://www.jumbo.com/aanbiedingen/zoete-punt-...,Jumbo,17 t/m 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
...,...,...,...,...,...,...
104,Disaronno [Kompas JumRouterLink],"Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/disaronno/3...,Jumbo,17 t/m 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
105,Jack Daniels [Kompas JumRouterLink],"Alleen in de slijterij 5,00 korting",https://www.jumbo.com/aanbiedingen/jack-daniel...,Jumbo,17 t/m 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
106,"Malibu likeur, Absolut vodka of Havana rum [Ko...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/malibu-like...,Jumbo,17 t/m 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
107,Malt Whiskies [Kompas JumRouterLink],"Alleen in de slijterij 6,00 korting",https://www.jumbo.com/aanbiedingen/malt-whiski...,Jumbo,17 t/m 23 jun,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...
108,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,4 feb t/m 30 dec,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...

In [5]:
df["date"] = df["date"].str.split("t/m")

def split_date(date_val):

    if isinstance(date_val, list):
        cleaned = ' '.join(str(x) for x in date_val)
    else:
        cleaned = str(date_val)

    cleaned = cleaned.replace('\xa0', ' ').replace('NBSP', '').strip()
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()

    same_month = re.match(r'(\d+)\s+(\d+)\s+(\w+)', cleaned)
    if same_month:
        day1, day2, month = same_month.groups()
        return f"{day1} {month}", f"{day2} {month}"

    diff_month = re.match(r'(\d+)\s+(\w+)\s+(\d+)\s+(\w+)', cleaned)
    if diff_month:
        day1, month1, day2, month2 = diff_month.groups()
        return f"{day1} {month1}", f"{day2} {month2}"

    return cleaned, cleaned

df[['start_date', 'end_date']] = df['date'].apply(
    lambda x: pd.Series(split_date(x))
)

In [6]:
df

,product,discount,link,store,date,image_url,start_date,end_date
0,Jumbo verse friet [Kompas JumRouterLink],"voor 1,99",https://www.jumbo.com/aanbiedingen/jumbo-verse...,Jumbo,"[17 , 23 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
1,Jumbo rauwkost [Kompas JumRouterLink],"voor 1,49",https://www.jumbo.com/aanbiedingen/jumbo-rauwk...,Jumbo,"[17 , 23 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
2,"Rucola, Veldsla of melanges [Kompas JumRouterL...","voor 1,00",https://www.jumbo.com/aanbiedingen/rucola-veld...,Jumbo,"[17 , 23 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
3,Nederlandse aardbeien [Kompas JumRouterLink],"voor 2,39",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,"[17 , 23 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
4,Zoete punt paprika mix [Kompas JumRouterLink],"voor 1,79",https://www.jumbo.com/aanbiedingen/zoete-punt-...,Jumbo,"[17 , 23 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
...,...,...,...,...,...,...,...,...
104,Disaronno [Kompas JumRouterLink],"Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/disaronno/3...,Jumbo,"[17 , 23 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
105,Jack Daniels [Kompas JumRouterLink],"Alleen in de slijterij 5,00 korting",https://www.jumbo.com/aanbiedingen/jack-daniel...,Jumbo,"[17 , 23 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
106,"Malibu likeur, Absolut vodka of Havana rum [Ko...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/malibu-like...,Jumbo,"[17 , 23 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
107,Malt Whiskies [Kompas JumRouterLink],"Alleen in de slijterij 6,00 korting",https://www.jumbo.com/aanbiedingen/malt-whiski...,Jumbo,"[17 , 23 jun]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
108,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,"[4 feb , 30 dec]",https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,4 feb,30 dec

In [7]:
df = df.drop("date", axis=1)
df

,product,discount,link,store,image_url,start_date,end_date
0,Jumbo verse friet [Kompas JumRouterLink],"voor 1,99",https://www.jumbo.com/aanbiedingen/jumbo-verse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
1,Jumbo rauwkost [Kompas JumRouterLink],"voor 1,49",https://www.jumbo.com/aanbiedingen/jumbo-rauwk...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
2,"Rucola, Veldsla of melanges [Kompas JumRouterL...","voor 1,00",https://www.jumbo.com/aanbiedingen/rucola-veld...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
3,Nederlandse aardbeien [Kompas JumRouterLink],"voor 2,39",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
4,Zoete punt paprika mix [Kompas JumRouterLink],"voor 1,79",https://www.jumbo.com/aanbiedingen/zoete-punt-...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
...,...,...,...,...,...,...,...
104,Disaronno [Kompas JumRouterLink],"Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/disaronno/3...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
105,Jack Daniels [Kompas JumRouterLink],"Alleen in de slijterij 5,00 korting",https://www.jumbo.com/aanbiedingen/jack-daniel...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
106,"Malibu likeur, Absolut vodka of Havana rum [Ko...","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/malibu-like...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
107,Malt Whiskies [Kompas JumRouterLink],"Alleen in de slijterij 6,00 korting",https://www.jumbo.com/aanbiedingen/malt-whiski...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
108,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,4 feb,30 dec

In [8]:
def product_clean(text):
    word = "[Kompas JumRouterLink]"
    text = text.replace(word, "").strip()
    return text

df["product"] = df["product"].apply(product_clean)
df

,product,discount,link,store,image_url,start_date,end_date
0,Jumbo verse friet,"voor 1,99",https://www.jumbo.com/aanbiedingen/jumbo-verse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
1,Jumbo rauwkost,"voor 1,49",https://www.jumbo.com/aanbiedingen/jumbo-rauwk...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
2,"Rucola, Veldsla of melanges","voor 1,00",https://www.jumbo.com/aanbiedingen/rucola-veld...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
3,Nederlandse aardbeien,"voor 2,39",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
4,Zoete punt paprika mix,"voor 1,79",https://www.jumbo.com/aanbiedingen/zoete-punt-...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
...,...,...,...,...,...,...,...
104,Disaronno,"Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/disaronno/3...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
105,Jack Daniels,"Alleen in de slijterij 5,00 korting",https://www.jumbo.com/aanbiedingen/jack-daniel...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
106,"Malibu likeur, Absolut vodka of Havana rum","Alleen in de slijterij 4,00 korting",https://www.jumbo.com/aanbiedingen/malibu-like...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
107,Malt Whiskies,"Alleen in de slijterij 6,00 korting",https://www.jumbo.com/aanbiedingen/malt-whiski...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
108,Welke biermerken zijn bij jouw Jumbo in de aan...,2e halve prijs,https://www.jumbo.com/acties/bieraanbieding,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,4 feb,30 dec

In [9]:
#removing products which are online or liquor store
df = df[~df["discount"].str.contains("Alleen online", case=True, na=False)]
df = df[~df["discount"].str.contains("slijterij", case=True, na=False)]
df = df[df['product'] != 'Welke biermerken zijn bij jouw Jumbo in de aanbieding?']

In [10]:
df

,product,discount,link,store,image_url,start_date,end_date
0,Jumbo verse friet,"voor 1,99",https://www.jumbo.com/aanbiedingen/jumbo-verse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
1,Jumbo rauwkost,"voor 1,49",https://www.jumbo.com/aanbiedingen/jumbo-rauwk...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
2,"Rucola, Veldsla of melanges","voor 1,00",https://www.jumbo.com/aanbiedingen/rucola-veld...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
3,Nederlandse aardbeien,"voor 2,39",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
4,Zoete punt paprika mix,"voor 1,79",https://www.jumbo.com/aanbiedingen/zoete-punt-...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
...,...,...,...,...,...,...,...
98,Alle Airwick,1+1 gratis,https://www.jumbo.com/aanbiedingen/alle-airwic...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
100,Muffins,"Alleen in de winkel voor 1,98",https://www.jumbo.com/aanbiedingen/muffins/301...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
101,Kaas of ham-kaas croissant,"Alleen in de winkel voor 0,49",https://www.jumbo.com/aanbiedingen/kaas-of-ham...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
102,Zespri kiwi Sungold,"Alleen in de winkel 2,99 per 500 gram",https://www.jumbo.com/aanbiedingen/zespri-kiwi...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
103,Trostomaten,"Alleen in de winkel 0,59 per 500 gram",https://www.jumbo.com/aanbiedingen/trostomaten...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun

In [11]:
def winkel(text):
    wink = "Alleen in de winkel"
    if wink in text:
        return text.replace(wink, "").strip()
    return text

df["discount"] = df["discount"].apply(winkel)
df

,product,discount,link,store,image_url,start_date,end_date
0,Jumbo verse friet,"voor 1,99",https://www.jumbo.com/aanbiedingen/jumbo-verse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
1,Jumbo rauwkost,"voor 1,49",https://www.jumbo.com/aanbiedingen/jumbo-rauwk...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
2,"Rucola, Veldsla of melanges","voor 1,00",https://www.jumbo.com/aanbiedingen/rucola-veld...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
3,Nederlandse aardbeien,"voor 2,39",https://www.jumbo.com/aanbiedingen/nederlandse...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
4,Zoete punt paprika mix,"voor 1,79",https://www.jumbo.com/aanbiedingen/zoete-punt-...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
...,...,...,...,...,...,...,...
98,Alle Airwick,1+1 gratis,https://www.jumbo.com/aanbiedingen/alle-airwic...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,30 jun
100,Muffins,"voor 1,98",https://www.jumbo.com/aanbiedingen/muffins/301...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
101,Kaas of ham-kaas croissant,"voor 0,49",https://www.jumbo.com/aanbiedingen/kaas-of-ham...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
102,Zespri kiwi Sungold,"2,99 per 500 gram",https://www.jumbo.com/aanbiedingen/zespri-kiwi...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun
103,Trostomaten,"0,59 per 500 gram",https://www.jumbo.com/aanbiedingen/trostomaten...,Jumbo,https://www.jumbo.com/INTERSHOP/static/WFS/Jum...,17 jun,23 jun

In [12]:
df.to_json('../../data/J_cleaned_7.json', orient='records', indent=4, force_ascii=False)